### ISSUE TITLE
How To Using Pop() In Vrouter?

### ISSUE THREAD

**Issue by leanhro2812** [lulupointu/vrouter#102]
I have a page
/abc and I push('/def')
How can I pop() to go back to the /abc trang page
I don't want to use push('/abc')
because it will create the effect of opening a new page instead of going back to the previous page.

**Comment by lulupointu** [comment]
You have to use `stackRoutes` to be able to pop.

Here are more details: https://vrouter.dev/guide/Advanced/Pop%20Events

The thing is that push is not really `push` but rather `pushReplacement` if you think like Nav1. I know it's poor naming, I will change it when I have the time 😉

Please tell me if you understood the stackedRoutes thingy 😊

**Comment by leanhro2812** [comment]
I'm on the Home screen right now
when i push('/another-screen')
1. Appbar doesn't show default pop button and I have to write a button myself to pop and rather it looks like it's not pop but push and using previousUrl : context.vRouter.push(context.vRouter.previousUrl);
Note : (window.history.back on browser doesn't work because as you said it is pushReplacement inherently)

2. When I pop with the button I wrote myself in my custom AppBar with action : context.vRouter.push(context.vRouter.previousUrl)
Then the previous Home screen will be pushed to . Then, on the Home screen, the pop() button appears again. When I press it . it goes back to /another-screen again. An endless loop

You can take a look at my AppBar:
```
class AppBarWidget extends StatelessWidget implements PreferredSizeWidget  {
  @override
  final Size preferredSize;

  final String title;
  final List<Widget> actions;
  AppBarWidget({
    @required this.title,
    this.actions,
  }) : this.preferredSize = Size.fromHeight(kToolbarHeight);

  @override
  Widget build(BuildContext context) {
    return AppBar(
      elevation: 0.0,
      title: Text(this.title),
      backgroundColor: Colors.white,
      leading: context.vRouter.previousUrl != null ? GestureDetector(
        onTap: () {
          context.vRouter.push(context.vRouter.previousUrl);
        },
        child: Container(
          child: Image.asset('assets/icons/icon_back.png'),
        )
      ) : null,
      actions: this.actions,
    );
  }
}
```

**Comment by lulupointu** [comment]
I'm not sure you did you stacked routes if you have this problem.

Here is a small example:
```dart
import 'package:flutter/material.dart';
import 'package:vrouter/vrouter.dart';

main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return VRouter(
      debugShowCheckedModeBanner: false,
      routes: [
        VWidget(
          path: '/',
          widget: HomeScreen(),
          stackedRoutes: [
            VWidget(
              path: '/settings',
              widget: SettingsScreen(),
            ),
          ],
        ),
      ],
    );
  }
}

class HomeScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
      child: Center(
        child: SizedBox(
          width: 200,
          height: 100,
          child: Container(
            decoration: BoxDecoration(
              border: Border.all(color: Colors.blueAccent, width: 3),
            ),
            child: Center(
              child: Column(
                mainAxisSize: MainAxisSize.min,
                children: [
                  Text('This is your home'),
                  SizedBox(height: 20),
                  ElevatedButton(
                    onPressed: () => context.vRouter.push('/settings'),
                    child: Text('Go to Settings'),
                  ),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
}

class SettingsScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Settings'),),
      body: Center(
        child: SizedBox(
          width: 200,
          height: 50,
          child: Container(
            decoration: BoxDecoration(
              border: Border.all(color: Colors.greenAccent, width: 3),
            ),
            child: Center(
              child: Text('Those are your settings'),
            ),
          ),
        ),
      ),
    );
  }
}
```

Also the issue with infinite looping is expected because `previousUrl` is the previousUrl you where on, not the previous in the navigation history.

**Comment by leanhro2812** [comment]
So we have to pop() infinitely like that?
I just went from the home page and moved to another page. And from this page I want to go back to home.
Why can I use pop() from home like that?
How can as soon as pop() returns to Home, the home page won't pop anywhere, because it's the original page?

**Comment by lulupointu** [comment]
As I said earlier, you are confused because `push` is not the same in `VRouter` as in `Nav1`.

Push replaces the entire `VRouteElement` stack with a new one, it does not really `push`. In this comment https://github.com/lulupointu/vrouter/issues/75#issuecomment-850957835 I explain in more details.

I know this is a hassle, I want to change the naming when I have the time, in the meantime please just think as `push` as a `to`. So `context.vRouter.push('/home')` is the same as `context.vRouter.to('/home')`.

**Comment by leanhro2812** [comment]
Sorry if I wasted your time
But I don't know how to
Home -> Settings
Then from Settings -> Home (I want to pop() to Home instead of push() to Home, As this will lead to endless looping)
and right at home we disable the back of the browser ?
Can't we just use Pop() for 2 independent routes?

**Comment by lulupointu** [comment]
You are not wasting my time, I am waiting yours with poor naming 😉

I think I don't really understand what you are trying to achieve because to me you are trying to achieve what I described in https://github.com/lulupointu/vrouter/issues/102#issuecomment-869502752

Maybe you could describe precisely what you want so that.

What concern me in what you say is when you say:
- I want to push instead of pop. Because pushing to /home or popping on /home is exactly the same for VRouter (as explained in the link I sent you: https://github.com/lulupointu/vrouter/issues/75#issuecomment-850957835) 
- You want to manually disable the pop, this is sometimes needed but for very particular cases so I don't think you need this. The backButton in the AppBar should appear automatically at the right time, as with Nav1

**Comment by leanhro2812** [comment]
I really need a true pop() event
I went through your Doc
But most like you said pop some url = push some url
When push will push new route into history
As for the pop I need it removed.
Because of
Page a => page B => Page OVER
When I pop from Page C => Page B and continue to pop page B => Page C
(What I wish it would be about Page A).
But almost all use is push()
So when pop() :
Page C => Page B => Page C => Page B => Page C => Page B .
Can you give me an example with 3 Pages
Page A [push to] Page B [push to] Page C
How to : Page C [pop to] Page B [pop to] Page A

**Comment by lulupointu** [comment]
Yes sure, 

here you go:
```dart
import 'package:flutter/material.dart';
import 'package:vrouter/vrouter.dart';

main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return VRouter(
      debugShowCheckedModeBanner: false,
      routes: [
        VWidget(
          path: '/',
          widget: HomeScreen(),
          stackedRoutes: [
            VWidget(
              path: '/settings',
              widget: SettingsScreen(),
              stackedRoutes: [
                VWidget(
                  path: 'fingerPrintSettings', // relative path
                  widget: FingerPrintSettingsScreen(),
                ),
              ]
            ),
          ],
        ),
      ],
    );
  }
}

class HomeScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
      child: Center(
        child: SizedBox(
          width: 200,
          height: 100,
          child: Container(
            decoration: BoxDecoration(
              border: Border.all(color: Colors.blueAccent, width: 3),
            ),
            child: Center(
              child: Column(
                mainAxisSize: MainAxisSize.min,
                children: [
                  Text('This is your home'),
                  SizedBox(height: 20),
                  ElevatedButton(
                    onPressed: () => context.vRouter.push('/settings'),
                    child: Text('Go to Settings'),
                  ),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
}

class SettingsScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Settings'),),
      body: Center(
        child: SizedBox(
          width: 200,
          height: 100,
          child: Container(
            decoration: BoxDecoration(
              border: Border.all(color: Colors.greenAccent, width: 3),
            ),
            child: Center(
              child: Column(
                mainAxisSize: MainAxisSize.min,
                children: [
                  Text('Those are you settings'),
                  SizedBox(height: 20),
                  ElevatedButton(
                    onPressed: () => context.vRouter.push('fingerPrintSettings'), // relative push
                    child: Text('Go to FingerPrintSettings'),
                  ),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
}

class FingerPrintSettingsScreen extends StatelessWidget {
  const FingerPrintSettingsScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Fingerprints Settings'),),
      body: Center(
        child: SizedBox(
          width: 200,
          height: 50,
          child: Container(
            decoration: BoxDecoration(
              border: Border.all(color: Colors.redAccent, width: 3),
            ),
            child: Center(
              child: Text('Those are you FINGERPRINTS settings'),
            ),
          ),
        ),
      ),
    );
  }
}
```

**Comment by leanhro2812** [comment]
If so, what will happen with 3 screens that do not stack on top of each other?
Can we use [back] or not?
A push to B , and B push to C
And after that . in C we go back to B and from B we go back to A?

```
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return VRouter(
      initialUrl: '/',
      debugShowCheckedModeBanner: false,
      theme: appTheme,
      mode: VRouterModes.history,
      routes: [
       VWidget(
            path: '/',
            widget: Container(
              child: Text('Home'),
            )
        ),
        VWidget(
            path: '/a',
            widget: Container(
              child: Text('Widget a'),
            )
        ),
        VWidget(
            path: '/b',
            widget: Container(
              child: Text('Widget b'),
            )
        ),
      ],
    );
  }
}
```

**Comment by lulupointu** [comment]
```dart
import dart:html as html

html.history.back
```

You can use this. I would like to include such a feature in VRouter but did not have the time yet

**Comment by lulupointu** [comment]
Also this only works on the web, if you need mobile you would need something else. Give me a week and I will add it into `VRouter` if you need.

**Comment by leanhro2812** [comment]
But for the example above, you probably already know where you're going.
As for the default Back Button.. we can't know where we just went to so the exact return
If using
```
context.vRouter.pushReplacement(context.vRouter.previousUrl);
```
We can only repeat at 2 screens together
For example:
At Screen D => Screen F => Screen K => Screen O
how do we get back to the correct route in reverse when you use push().
If you are at Screen O and want to go back
```
context.vRouter.pushReplacement(context.vRouter.previousUrl);
```
then it will return to screen K.
but in the K screen.
when you want to come back
```
context.vRouter.pushReplacement(context.vRouter.previousUrl);
```
then it goes back to Screen O.
It cannot go back to F

**Comment by lulupointu** [comment]
I agree that in your case you might want a custom back button.

The issue with previousUrl is that it's really the previous url so when you do 
`Screen D => Screen F => Screen K => Screen O`

then previous url is `Screen K`. If from O you go to K, then previousUrl is O.

What you need is different and is more like the browser back button. It is not yet available in VRouter but I can certainly make it.

**Comment by leanhro2812** [comment]
Yes, Thank you so much for your time
I look forward to Vrouter's updates
I like Vrouter very much compared to other things.
I will keep an eye on pub.dev for the most up-to-date version of this issue.
Hope. :)

**Comment by lulupointu** [comment]
I'll update you here when it's done.

You can join the discord server if you want notification of the updates and changes :)

**Comment by leanhro2812** [comment]
> I'll update you here when it's done.
> 
> You can join the discord server if you want notification of the updates and changes :)

Please give me invite link discord :)

**Comment by lulupointu** [comment]
Just click on the discord shield on pub.dev on Github 😉

I'm not sure of what you want. My AppBar are all depending on stackRoutes and pop atm. What you want is not currently possible that's why I will update VRouter

**Comment by leanhro2812** [comment]
> Just click on the discord shield on pub.dev on Github 😉
> 
> I'm not sure of what you want. My AppBar are all depending on stackRoutes and pop atm. What you want is not currently possible that's why I will update VRouter

Yes, thank you very much.
Expect the update soonest  :)

**Comment by johnwangwjq** [comment]
Hi @lulupointu, sorry for re-active this issue as me has problem to understand the same. 

Need you help to understand some key concepts:

1. When talking about navigation in a general sense(ie., both in flutter and vroute specifically), a pop mean remove and poping up the latest screen in a particalur "navigation stack". correct? In this context a "navigation stack" in vrouter is what we setup in the `stackedRoutes`(like you example code above). right? a pop operation can and only can work on a `stackedRoutes`, right?
2. Since the vanilla flutter builtin `Navigator.of(context).push()` and `Navigator.of(context).pop()` works well, does that means `Navigator.of(context).push()` is actuall pushing on a particual "navigation stack" something just like a  `stackedRoutes` of vrouter?
3. If the above 2 points are understood right, the whole navigations of an application is usually a bounch of `stackedRoutes` which in turn contains lots of `VWidget`. It's like a forrest. Each tree in the forrest is a `stackedRoutes`. When you do a relative `push`, you move in a particular tree. when you do an absolute push(ie., push to a path starting with a "/"), you jump from a tree to another. when you `pop` you really just move in a particular tree. there is no way for you to jump from a tree to another by a `pop`. phew! hope I'm understand right!

**Comment by lulupointu** [comment]
@johnwangwjq 

**assertion 1** is **true**
**assertion 2** is **somewhat true**: `Navigator.push` does not change the stack of `VRouteElement`s. However it pushes on top of the Navigator stack, which is the stack stack VRouter uses to stack the widget (or pages) you give in `VWidget.widget`.
**assertion 3** is **true** from a theoretical aspect. In practice, if you are in `/user` and use `push("settings")` OR `push(/user/settings)`, both are equivalent. And the same is true for pop, this is why I say `pop` = `push`, because `pop` is just a way to get a new path, which is then used to do `push(newPath)` (basically)

**Comment by lulupointu** [comment]
@leanhro2812 the features is coming. It is implemented and tested, I just need to update the documentation because I'm doing other changes in VRouter 1.2. I'll let you know when it's out but just wanted you to know it's going well :wink:

**Comment by johnwangwjq** [comment]
I'm all set. After so long a time, the whole document start to make sense to me now. 

Thank you so much @lulupointu. Have a good day!

**Comment by lulupointu** [comment]
https://user-images.githubusercontent.com/5128921/124136418-0d164180-da85-11eb-9161-c73fe1173f1b.mp4

Here is a preview of the feature :wink: 

<details>
<summary>
Here are the `routes`
</summary>

```dart
VNester(
  path: null,
  widgetBuilder: (child) => MyScaffold(child: child),
  nestedRoutes: [
    VPopHandler(
      onSystemPop: (vRedirector) async {
        if (vRedirector.urlHistoryCanBack()) {
          vRedirector.urlHistoryBack();
        }
      },
      stackedRoutes: [
        VWidget(
          path: '/',
          widget: BasicScreen(title: 'home'),
        ),
        VWidget(
          path: '/social',
          widget: BasicScreen(title: 'social'),
        ),
        VWidget(
          path: '/settings',
          widget: BasicScreen(title: 'settings'),
        ),
      ],
    ),
  ],
)
```

</details>

Don't hesitate to tell me what you think !

**Comment by leanhro2812** [comment]
@lulupointu 
I will wait for the latest version to experience
By the way.
Don't know if you should add "Back" will have the opposite effect than pushing to a new page
Like your demo above
Android:
When it comes to a new page, it slides from bottom to top
When we leave it (Back) the page itself will slide from top to bottom

Ios:
When you reach a new page, it will slide from right to left
When we leave the page (Back), it will slide from left to right

Thank you for your time.
  I can't wait to experience the latest changes.

**Comment by lulupointu** [comment]
@leanhro2812 "pushing" was not really a good name and I don't think the concept applies to VRouter because:
  - `pop` if for popping in stackedRoutes
  - `back` is for going back in the url history
What you describe feels more like the former (pop) and is fully handled by `stackedRoutes`. Their is a reason this cannot be changed but I don't think this is limiting. 

Also `v1.2` is out, and with it the changes mentioned above. This was quite challenging to implement so I hope everything is working but do open an issue if needed! Also check out the example here https://vrouter.dev/guide/Examples/History (@johnwangwjq  as well I think you where interested in this!)

I'm going to close this since it was more of a feature request but open a new issue if you have a specific issue with the new history API :wink:
