### ISSUE TITLE
Suggestion to pass objects via vRouter

### ISSUE THREAD

**Issue by ebelevics** [lulupointu/vrouter#122]
Isn't it possible to do with RouteSettings class? For example:       

```
context.vRouter.to(
        RegisterCompleteScreen.routeName,
        arguments: MyDataObject(),
      );
```

```
VWidget(
  path: LoginScreen.routeName,
  widget: (context, arguments) => LoginScreen(arguments.data as MyDataObject),
),
```

_Originally posted by @ebelevics in https://github.com/lulupointu/vrouter/issues/111#issuecomment-881836141_

**Comment by lulupointu** [comment]
This could theoretically be implemented. However the issue is not whether it's possible or isn't, the issue is whether we should be able to do so or not.
It is my belief that this should not be implemented, because of how I see app navigation.

The reason is that navigation != state management. And passing data as you do is a form of state management.

One concrete issue is that with `arguments`, you have to think about where you come from. This means that it's really easy to forget to pass the `arguments` when navigating to `LoginScreen.routeName` from a new place. Even worse, if you carefully remind yourself that you should always pass `arguments`, you might think `arguments.data` will never be null. However if you add deep-linking to your app (which are always here for the web for example), `argument.data` **will be null** this time.

Only looking at the above mentioned problem you can understand that there is an issue, we need to *remember* and *think about all scenarios*, both things we would rather not do as developers. Using a state management library and making it interact with VRouter is way more effective since there are often built to make you think about your usecases.


Feel free to argue or ask for clarification if needed. It's definitely an interesting subject on which I'm always pleased to here what others think :wink: !

**Comment by ebelevics** [comment]
Thank you for your answer. I'll probably will tell little background. Right now I'm doing medium-large mobile app, which requires separating features in modules. Coming from Navigator 1.0 it gets messy pretty fast, learning and implementing it on Navigator 2.0  just didn't feel 1.0ish enough and it got complicated really fast. So I was looking for Navigator 2.0 wrapper and found https://github.com/flutter/uxr/blob/master/nav2-usability/comparative-analysis/README.md. First I tried flutter_modular, while it did separate features it just felt lackluster. After inspecting others packages I found VRouter had great github issue management, concise tutorial website (similar to https://bloclibrary.dev/), no code generation and package overall feels more robust and clean. So this built me trust. 

But while web routing seemed precise (having experience in Laravel), for my mobile app needs routing seemed hard to grasp. The Custom VRouteElement and Scaling felt amazing for modularity, but stacking pages independently from different modules seems cumbersome. 

For example, I thought stackedRoutes[Login(path:"auth/login)", Register(path:"auth/register:)] parameter would let me stack pages in navigation order, but it replaces previous page, which is not what I need. And putting stacked pages (like login->register->confirm register) in multiple stackedRoutes seems wrong for mobile app (I do understand for web app). What if I would want do navigate to "register" initially? As I was testing it did open as (login->register) not as (register) as I was expecting.

And so I also stepped to object passing. But I do agree I can manage it with Bloc for example.

Otherwise at first impression it seemed more suited for webapps but I hope I'm wrong and it's because I'm still trying to understand this package. 

little offtopic:
Also my observation and guess is that packages with easier transition and similar feed to old methods gain more popularity despite it's quality or support at first glance.

**Comment by ebelevics** [comment]
I'm currently working on medium-large mobile app project, that's why manageable and maintainable structure (inspirited from Reso Coder TDD videos) was important feature. It would be great to see how exactly vRouter is implemented in medium-large scale mobile apps with approx. 7-10 screens. But that's just my opnion.
But so far I found solution how I can make modules within Navigator 1.0 inspired ideas from this package examples and other, so I'm switching back. But I'll keep and eye on this package and test history.

The support is great tho. I'm closing it now.

**Comment by lulupointu** [comment]
I would love to have the time to explain how to make this work. I am working with clean architecture as well (though not exactly as Reso coder does) and it's working great.

The main idea is to have interfaces for navigation, and use them by relying on DI.

**Comment by ebelevics** [comment]
I really love again how https://bloclibrary.dev/#/flutterfirestoretodostutorial explains his examples - it's clean, structured and visually informative. The additional section for example apps in vrouter.dev would be great addition, tho it would additional require maintenance for breaking changes.

But yeah I do agree the navigation should have easily accessible feature separated interface.

For example I'll share current implementation for "profile" feature routing.

```
class ProfileRoutes extends Routes {
  @override
  final String path = "home/profile";

  @override
  Widget? nestedRoutes(BuildContext context, RouteSettings settings) {
    super.nestedRoutes(context, settings);

    if (settings.name == ProfileScreen.routeName) return ProfileScreen();

    if (settings.name == ProfileAccountScreen.routeName)
      return ProfileAccountScreen();

    return ErrorScreen();
  }

  @override
  Widget? routes(BuildContext context, RouteSettings settings) {
    super.routes(context, settings);

    if (settings.name == ProfileAccountAboutScreen.routeName)
      return ProfileAccountAboutScreen();

    if (settings.name == ProfileAccountImageScreen.routeName)
      return ProfileAccountImageScreen();

    if (settings.name == ProfileAccountPasswordScreen.routeName)
      return ProfileAccountPasswordScreen();

    if (settings.name == ProfileAccountRemindersScreen.routeName)
      return ProfileAccountRemindersScreen();

    return ErrorScreen();
  }
}
```

nestedRoutes similary like vRouter are accessed with bottomNavBar Navigators, which changes or pushes or pops new nested screen. routes function will push to rootNavigator new screen on stack which will fill all mobile screen. And all the Routes (abstract class) are connected to MaterialApp widget, which at the end is just a widget as a child to MaterialPageRoute.
