### ISSUE TITLE
Pass data 'back' via .pop(..) ?

### ISSUE THREAD

**Issue by SogoGolf** [lulupointu/vrouter#132]
In some nav libraries you can pass data "back" in a callback to the .to(..) method. How do we achieve the same thing with VRouter ?

eg.
**screen 1**
```var response = await context.vRouter.to('/selectClub');```

**Select Club Screen**
<.... do stuff..>
```context.vRouter.pop();```

How can we pass some data back to **screen 1** ? eg. {strokes: 6, par: 3}. eg. ```context.vRouter.pop(data: {strokes: 6, par: 3});```

**back in screen 1....** 
```var response = await context.vRouter.to('/selectClub');
print(response.data.strokes)
```

The above is obviously incorrect in terms of how to call vRouter methods but hopefully illustrates what I mean / am looking for.

**Comment by lulupointu** [comment]
I understand what you are looking for, unfortunately there is no way of doing so for several reasons:
  1. Popping does not really pop, as you said it's incorrect but more fundamentally this is not something nav2 (or the router) API offers
  2. The second best solution would be to be able to set a `state` object on the router. Like `Navigator.to(..., state: myObjectToPass)`. This issue here however, is that on the web refreshing will loose this object and there is no easy solution for this. 
  3. There are other issues but I believe those 2 to be the most problematic

**Comment by lulupointu** [comment]
I understand what you are looking for, unfortunately there is no way of doing so for several reasons:
  1. Popping does not really pop, as you said it's incorrect but more fundamentally this is not something nav2 (or the router) API offers
  2. The second best solution would be to be able to set a `state` object on the router. Like `Navigator.to(..., state: myObjectToPass)`. This issue here however, is that on the web refreshing will loose this object and there is no easy solution for this. 

There are other issues but I believe those 2 to be the most problematic.

What is the solution? To me there are 2:
  1. If you simply want to show a confirmation dialog, use navigator 1 (final shouldX = `showDialog`)
  2. If you need something more complex, use some state management library to pass your data around, provider being a simple option

Hope this helps, sorry it's not easier, it's a pain for me too and I've been thinking a lot about this issue but cannot find a good-easy solution

**Comment by esDotDev** [comment]
I think the best way to think of this, is how would a web page pass this data to another web page? There's kinda 2 solutions, either pass it via args, or store it in session (aka your app state).

So basically page 2 can not pop here, instead it needs to do `.to('page1?strokes=6&par=3')`, or something funky like: `appState.page2ReturnValues = {}`

**Comment by lulupointu** [comment]
Thanks for the comment @esDotDev, this is accurate.

I will close this since @SogoGolf has not answered for 30 days, feel free to reopen if needed.
