### ISSUE TITLE
VRouter() the named parameter 'scaffoldMessengerKey' isn't defined.

### ISSUE THREAD

**Issue by mdrideout** [lulupointu/vrouter#136]
SnackBars managed by the ScaffoldMessenger require a scaffoldMessengerKey to be passed to the MaterialApp() widget. [See docs](https://flutter.dev/docs/release/breaking-changes/scaffold-messenger).

Is there a way to use VRouter without replacing the MaterialApp() widget?

**Comment by lulupointu** [comment]
From what I understand, you don't need a `scaffoldMessengerKey`. You only need it if you need to access the `ScaffoldMessenger` without a `context`. Is that what you are trying to do ?

If so, I would suggest putting the `ScaffoldMessager` yourself in the widget tree, just bellow `MaterialApp` be using `VRouter.builder`. When doing so:
  1. Any scaffold will be registered to yours and not the `MaterialApp`'s since yours is bellow
  2. You can given the key to the scaffold messenger since you create it yourself

For completeness of the answer - Yes there is a way to use `VRouter` without `MaterialApp`, see this: https://github.com/lulupointu/vrouter/issues/51#issuecomment-827729566 (I would use a statefullwidget and put `VRouterDelegate` in the state though, but appart from that everything is said there.

Let me reaffirm that I don't think you need to put `MaterialApp` manually, simply inserting a `ScaffoldMessager` is better.
