### ISSUE TITLE
Bug: Pop using AppBar X button returns to route without previous query params

### ISSUE THREAD

**Issue by amitkot** [lulupointu/vrouter#154]
## Steps
1. Navigate to `first` route using some query parameter (e.g. {'X': 'true'})
2. Navigate to a stacked route (`second`) which is defined as a full-screen-dialog
3. Return to previous route using AppBar's X (close) button

## Expected
Return to `first` route with the same query parameter that was previously set

## Actual results
Return to `first` route with no query parameter set

## Logs
```
[VRouter: INFO] Successfully navigated to "/" using VRouter.to 
[VRouter: INFO] Successfully navigated to "/first?X=true" using VRouter.to 
[VRouter: INFO] Successfully navigated to "/first/second" using VRouter.to 
[VRouter: INFO] Successfully navigated to "/first" using VRouter.pop 
```

Example project: https://github.com/amitkot/vrouter_bug

**Comment by amitkot** [comment]
Thanks, `historyBack` works fine for my needs!

Why is the current behavior the intended one? Would you not expect a Navigator.pop() to return to the exact previous screen, with the same params?

**Comment by lulupointu** [comment]
I understand that your use case is different. However since the API has to:
  1. Take everything into account
  2. Be consistent (which is very important for easy use)

the current behavior is the best one.

If you need another argument, VRouter is *not* a state management library. It's important that the 2 are separate since VRouter would make a poor state management library, and having bits of it would not help. This is a strong choice but explains a lot of things (like why you can't pass an arbitrary `state` object during push), including this.

I hope you understand. If you need my advice on how to implement it I think:
  -  `historyBack` is a good option if you are sure to only come from the route bellow
  - Otherwise I would use `to('/pathBellow', queryParameters: Uri.parse(context.vRouter.previousUrl ?? '').queryParameters)`

**Comment by amitkot** [comment]
I understand your points, thanks!

**Comment by baconcheese113** [comment]
`historyBack` is a good option when needing to navigate back, but is there an eloquent solution for when the user taps the phone's back button or presses the back button in the AppBar? I will always want the queryParameters preserved when navigating back

**Comment by BarRemisz** [comment]
@baconcheese113 you can do: 
```dart 
return VRouter(
  //other params
   onSystemPop: (vRedirector) async {
              if (vRedirector.historyCanBack()) {
                vRedirector.historyBack();
              }
            },
```
