### ISSUE TITLE
Rebuild widgets in stackedRoutes

### ISSUE THREAD

**Issue by minhnhatvdl** [lulupointu/vrouter#157]
I have 2 routes:
 /home -> HomeWidget
 /home/user -> UserWidget

 VWidget(
            path: '/home',
            widget: const HomeWidget(),
            stackedRoutes: [
              VWidget(
                path: 'user',
                widget: const UserWidget(),
              )
          ]
)

I go to /home firstly, HomeWidgets is built. But when i navigate to /home/user, the HomeWidget is rebuilt.
Anyone has the same problem as me ?

**Comment by lulupointu** [comment]
This is not any issue but a feature.

[Here is why this is not an issue](https://stackoverflow.com/a/52249579/5990125)

And this is a feature because: If `HomeWidget`needed to load something where the path changed, here would be its opportunity of doing so

**Comment by lulupointu** [comment]
Closing this issue in absence of response. Feel free to reopen if you need more clarifications.

**Comment by Paolo-N** [comment]
Hi @lulupointu, I really appreciate your work, thanks.
I'm approaching navigation and using your package, I think I have a similar problem.

In my case i have:

```
        VWidget(path: '/', widget: const HomePage()),
        VWidget(
          path: '/configurator',
          widget: const ConfigurationsPage(),
          stackedRoutes: [
            VWidget(
              path: 'configurations',
              widget: const ConfigurationsPage(),
              stackedRoutes: [
                VWidget(
                  path: 'view/:code',
                  widget: const ConfiguratorPage(),
                  stackedRoutes: [
                    VWidget(
                      path: ':revision',
                      widget: const ConfiguratorPage(),
                    ),
                  ],
                ),
              ],
            ),
            VRouteRedirector(path: ':_(.+)', redirectTo: '/configurator'),
          ],
        ),
```

In `ConfiguratorPage` I have a stateful widget which perform an http call in `InitState`.

When i visit `/configurator/configurations/view/CFG00005/1` it calls `InitState` twice, so I have 2 questions:

1. Why it tries to build `/configurator/configurations/view/CFG00005` if I never navigate into it?
2. How should I approach this or similar situations?

Thanks again.

**Comment by lulupointu** [comment]
1. Why it tries to build `/configurator/configurations/view/CFG00005` if I never navigate into it?

This is because you are stacking 2 `ConfiguratorPage` when going to `/configurator/configurations/view/CFG00005/1`. So 2 instances are (independently) created.

2. How should I approach this or similar situations?

I would use something to share data between the two pages. The easiest way would be to use a state management package. 

Basically you want to:
  1. Inject your dependencies (i.e. place your `Provider` or `BlocProvider`) above `VRouter`
  2. Use a method on the provided object (or emit an event in the case of bloc) to initialize you object if its not already initialized
  3. Find a way to dispose of you object (<- This is quite hard and depend on the situation, but will likely be done right before navigating away when/if needed)

The third step is quite hard because state management packages tie their state cycles to widget lifecycle. This is an issue here since the widget living above `VRouter` would never be disposed of. An easier way to achieve this is to use `riverpod`, which lifecycle are independent of the widget lifecycle. However this is beyond the scope of this answer ^^

**Comment by Paolo-N** [comment]
> This is because you are stacking 2 `ConfiguratorPage` when going to `/configurator/configurations/view/CFG00005/1`. So 2 instances are (independently) created.

Ok I got it, I think I need to study more the framework, but I undestand that calling build is not actual rendering.

> I would use something to share data between the two pages. The easiest way would be to use a state management package.

This is a good starting point, I'll dive into it.

Anyway thanks to the first answer I changed this:

```
                VWidget(
                  path: 'view/:code',
                  widget: const ConfiguratorPage(),
                  stackedRoutes: [
                    VWidget(
                      path: ':revision',
                      widget: const ConfiguratorPage(),
                    ),
                  ],
                ),
```

Into this:

```
                VWidget(
                  path: 'view/:code',
                  widget: const ConfiguratorPage(),
                  aliases: const ['view/:code/:revision'],
                ),
```

And it works as exepected.

Thanks for your reply, it clarified some blutty concepts in my mind!
