### ISSUE TITLE
VRouter and animations' OpenContainer

### ISSUE THREAD

**Issue by amitkot** [lulupointu/vrouter#161]
When using [animations](https://pub.dev/packages/animations)'s `OpenContainer` one defines the navigation in an imperative way - you use the [OpenContainer widget](https://pub.dev/documentation/animations/latest/animations/OpenContainer-class.html) and provide it with `closedBuilder` (and `closedBuilder`) builder functions that are provided with and `action` callback for navigating to and from the "container" screen.

The animation easily provides a "professional" looking animation and is relatively simple to use.

From the context of a navigation package, I think that what I would hope to have is a way to get to the "openedContainer" state both by clicking on the OpenContainer class, and by deep-linking directly to the screen. 
As a user, I would expect that when I click the widget and the container "opens", the URL (in case this is on web) will change to the deep-link URL automatically, so that I could copy+paste it in a different window, share, or save it.

Do you think this is an experience that can be achieved with VRouter?

**Comment by lulupointu** [comment]
I have no experience with `OpenContainer` directly but this seems to be like any other animation widget (like `FadeTransition`). 

Have you read [the "Animations" part of the VRouter documentation](https://vrouter.dev/guide/Advanced/Transitions)?

**Comment by amitkot** [comment]
Thanks for the reference to the transitions! 
The issue here is a bit different, though. 
I created a demo - https://github.com/amitkot/vrouter_opencontainer

See the difference in the URL when you access the page using the deep-link (e.g. https://0.0.0.0:8080/#/1) and when you  click on the "1" tile.
Both actions result in the same screen, but only when accessing the deep-link you get the URL "updated" with a reproducible link.

What I am looking for is a way to get the URL updated with "1" when the screen changes to the `ItemScreen` one.

Perhaps something along the lines of:

```dart
void onInit(...) {
  if (widget.id == null) {
    final itemId = context.vRouter.pathParameters['id'];
    context.vRouter.updateUrlTo('/$itemId');
  }
}
```

**Comment by lulupointu** [comment]
I see, indeed this is not really the same.

Indeed you should you something like what you wrote **however** what you wrote is not enough. You have to take every case into account:
  - Url -> state for `/`
  - state -> Url for `/`
  - Url -> state for `/:id`
  - state -> Url for `/:id`

Basically this is a pain in the ** because `OpenContainer` is written imperatively, meaning that you have to react to every changes considering every situation. 
If `OpenContainer` was declarative, it would have a `isOpen` field, which would eliminate everything else. Anyway sorry for not having a simpler answer. I just spend 30 minutes trying to make this work and there are still edge cases so...

**Comment by lulupointu** [comment]
Gosh this works *really* poorly with `VRouter`, after further attempt the two are really fighting each other.

Here is the perfect example of how stupid this is:

`OpenContainer` uses Nav1 to open -> You navigate to `/1` -> `VRouter` dismisses all `Nav1` routes before navigating (because Nav1 routes are normally dialogs that you want to close before navigating) ->  `OpenContainer.onClosed` is called while what you are trying to do is to open the damn thing 🤯

**Comment by lulupointu** [comment]
I don't know if you need  `OpenContainer` but maybe using a `Hero` instead could do the trick ?

<details>
<summary>
Here is a small example
</summary>

```dart
import 'package:flutter/material.dart';
import 'package:vrouter/vrouter.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return VRouter(
      title: 'Flutter Demo',
      routes: [
        VWidget(
          path: '/',
          widget: const ListScreen(),
          stackedRoutes: [
            VWidget.builder(
              path: ':id',
              builder: (_, state) => ItemScreen(id: int.parse(state.pathParameters['id']!)),
              buildTransition: (_, __, child) => child,
            ),
          ],
        ),
      ],
    );
  }
}

class ListScreen extends StatelessWidget {
  const ListScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: ListView(
        children: [
          Hero(
            tag: '1',
            child: Material(
              color: Colors.greenAccent,
              child: Center(
                child: ListTile(
                  leading: const Text('1'),
                  onTap: () {
                    context.vRouter.to('/1');
                  },
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }
}

class ItemScreen extends StatelessWidget {
  const ItemScreen({
    required this.id,
    Key? key,
  }) : super(key: key);

  final int id;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('$id'),
      ),
      body: Hero(
        tag: '$id',
        child: Material(
          color: Colors.greenAccent,
          child: Center(
            child: Text('Item screen: $id'),
          ),
        ),
      ),
    );
  }
}
```

</details>

**Comment by lulupointu** [comment]
Closing in absence of response. Feel free to reopen if you have more questions.
