### ISSUE TITLE
Allow pages to stop from navigating away, e.g. if there are unsaved state changes

### ISSUE THREAD

**Issue by Josua2012** [lulupointu/vrouter#166]
Hello,
I am going to start a web project with Flutter, for another project use the Fluro library, however, I could not solve the following problem:
If a user is on a page that contains a form and is making modifications is said form, I would like that if he tries to exit without having saved the modifications (either by putting another url, with the browser's backbutton, ...) it would show him an alertdialog giving him the possibility of canceling the navigation to the new url or, on the contrary, of canceling the modifications and staying on the same page where he is.
The question is, can I do this with vrouter?
vrouter has any mechanism by which this functionality can be achieved?
Please, if this functionality is possible with vrouter could you give me some indications.
Thank you so much for all the help.
Regards,
Jose

**Comment by lulupointu** [comment]
Hi,

I think you will have a hard time finding a ready-to-go solution because Flutter does not implement this (and therefore many of the libraries build on top of Flutter do not). 
I did see a discussion about this on the Flutter repo (I don't have the reference unfortunately).
I see 2 solutions to your issue (both should be applied):
  1. Find the issue in the Flutter repo, upvote it and explain your use case in the comment
  2. In the meantime, implement your own solution. This should not be too hard with the `dart:html` package since it provide easy interactions with the browser native functionalities.

I will close this for now, feel free to reopen if needed
