### ISSUE TITLE
[Question] How can I get the pathParameter inside VRouteElementBuilder

### ISSUE THREAD

**Issue by grayWFG** [lulupointu/vrouter#179]
I have a route structure below:

```dart
class RootRoute extends VRouteElementBuilder {
  @override
  List<VRouteElement> buildRoutes() {
    return [
      VNester(
        path: '/user/:userId',
        widgetBuilder: (child) => child,
        nestedRoutes: [UserRoute()],
      ),
    ];
  }
}

class UserRoute extends VRouteElementBuilder {
  @override
  List<VRouteElement> buildRoutes() {
    // can I get the current/parent path or path parameter "userId" here?
    return [];
  }
}
```

I want to use the path to do something (like redirect to another path with id with VRouteRedirector)
but don't know how when part of the path is in the path parameter.

Thank you

**Comment by lulupointu** [comment]
Hi,

You can't get it in buildRoutes. This is because if your routes bellow have an absolute path, `userId` would not exists, therefore `VRouter` can't pass path parameters like that. 

I would suggest adding 2 different `VNester` depending on the kind of path you want to match instead. You can use regexp inside the `VNester.path` to achieve that. If you need help tell me what are the different forms of `userId` you want to match and I could give it a go.

**Comment by grayWFG** [comment]
I original want to add multiple id in my route path like below:

User select page:          /user
Selected user's Home:  /user/:userId/home
Selected user's book:   /user/:userId/home/:bookId/detail

but sometimes I want to 
1. check the path is valid or not and redirect it: (redirectTo target need the userId)
/user/:userId/notavalidpath => redirect to /user/:userId/home
/user/:userId/home/notexistbookid => redirect to /user/:userId/home

2. use relative paths to all the VRouteElements and make the code look more structured.
(that is why I want to get the parent path inside the VRouteElementBuilder.)

Is it a valid usage of the path parameters? How can I achieve the goal?

**Comment by lulupointu** [comment]
I understand that you want to keep relative path. Unfortunately since this is not a restriction in VRouter it means that what you are trying to do is not directly possible.

However, I admit that there is something missing to make this easy. So I added a `VRedirector.parse` constructor, which you can use like this

```dart
VRouteRedirector.parse(
  redirectTo: (vRedirector) {
     vRedirector.to('/user/${vRedirector.newVRouterData!.pathParameters['userId']}/home');
  } ,
  path: r'/user/:userId/*',
)
```

Hope this helps !

**Comment by grayWFG** [comment]
I think that's good enough for me. Thank you!
