### ISSUE TITLE
[Feature request] add ability to push single Page into the history stack

### ISSUE THREAD

**Issue by TatsuUkraine** [lulupointu/vrouter#187]
So the future as simple as it is) allow to push a single page to the history stack by name or route path. Currently, it's possible to this by using `Navigator.push(context, ....);`

The problem is that it's not quite convenient. Instead, it would be good to have something like `context.vRouter.push('/settings',...)` (I understand that it is a deprecated method currently))) or `context.vRouter.pushNamed('settings',...)`. Which will find a propper page, that matches the name or route, wrap target page with Material/CupertinoPageRoute and invoke `Navigator.push(context, pageInstance)`

**Comment by lulupointu** [comment]
Hi, since `VRouter` is fully declarative, it is not my intention to support this any other way than using `Navigator.push`.

I understand that this can be a limitation however I have not found a satisfying way of enabling this while keeping a declarative approach (i.e. no `push`, only `to`).

Let my know if you have an idea by reopening this issue :)
