### ISSUE TITLE
Path matching with * instead of regexp

### ISSUE THREAD

**Issue by theweiweiway** [lulupointu/vrouter#29]
Hey lulu,

Version 1.x is super slick, wow! Amazing stuff, and the API feels incredibly intuitive

Anyways, I was just wondering if you had plans to support path matching based on * wildcards, since it seems to be a common way of matching paths (I'm thinking of things like react router, Express Js)

Thanks for all the hard work,
Weiwei

**Comment by lulupointu** [comment]
Hi,

Thanks! 

The short answer is no. 

The long answer is here https://github.com/leonsenft/path_to_regexp/issues/18

Of course this can change if I see that it's really too much for people to learn the ".+" RegExp, but since I use it several time in every tutorial I am hoping that it's not.
Moreover the RegExp support is so powerful (I use it for some of my apps) that I really don't feel like make it a second class citizen.
Once again, this can change depending of package user of course 😉

**Comment by theweiweiway** [comment]
I see where he's coming from, ok! Yes, matching by Regexp is very powerful and it's honestly isn't that bad to use Regexp instead of wildcards

I'll be closing this then, thanks~!
