### ISSUE TITLE
Bug: VRouter multiple route stacking does not work when path has params.

### ISSUE THREAD

**Issue by satvikreddy** [lulupointu/vrouter#30]
I am trying to achieve stacking of 3 views in flutter android app.
View1() -> View2() -> View3()

**Expectation**: Tapping back on View3 should go to View2.

**Working Code**:
`routes: [
        VWidget(
          path: "/",
          widget: View1(),
          stackedRoutes: [
            VWidget(
              path: "/two",
              widget: View2(),
              stackedRoutes: [
                VWidget(
                  path: "/three",
                  widget: View3(),
                ),
              ],
            ),
          ],
        ),
      ],`

**Working gif**
![working](https://user-images.githubusercontent.com/16370824/113264439-9be1b980-92f0-11eb-8259-e6cdec490fd3.gif)

**Code that breaks**:
When View2 path contains params, back button on View3 directly closes the app instead of popping views.

`routes: [
        VWidget(
          path: "/",
          widget: View1(),
          stackedRoutes: [
            VWidget(
              path: "/two/:id",
              widget: View2(),
              stackedRoutes: [
                VWidget(
                  path: "/three",
                  widget: View3(),
                ),
              ],
            ),
          ],
        ),
      ]`

**Breaking gif**:
![breaking](https://user-images.githubusercontent.com/16370824/113264649-d51a2980-92f0-11eb-8383-1f12c71c4095.gif)

**Comment by lulupointu** [comment]
This is not a bug, it's a feature 👍

If you are on "/three" and want to go to "/two/:id", how does VRouter know what is the id?

There are 2 solutions to your problem:
1. Use a relative path
2. Don't use ":id" in the path
3. Use a VPopHandler and a custom key

### 1. Using a relative path

```dart
  runApp(
    VRouter(
      routes: [
        VWidget(
          path: "/",
          widget: View1(),
          stackedRoutes: [
            VWidget(
              path: "/two/:id",
              widget: View2(),
              stackedRoutes: [
                VWidget(
                  path: "three",
                  widget: View3(),
                ),
              ],
            ),
          ],
        ),
      ],
    ),
  );
```
This is the easiest solution, since you are specifying the id, VRouter is smart enough to use the same when the back button is pressed.


### 2. Use a VPopHandler and a custom key

```dart
  runApp(
    VRouter(
      routes: [
        VWidget(
          path: "/",
          widget: View1(),
          stackedRoutes: [
            VWidget(
              path: "/two",
              widget: View2(),
              stackedRoutes: [
                VWidget(
                  path: "/three",
                  widget: View3(),
                ),
              ],
            ),
          ],
        ),
      ],
    ),
  );
```

This might seem silly but if you are only on mobile and do not care about link sharing, this might actually be a solution

### 3. Use a VPopHandler and a custom key

```dart
VRouter(
  routes: [
    VWidget(
      path: "/",
      widget: View1(),
      stackedRoutes: [
        VWidget(
          path: "/two/:id",
          widget: View2(),
          key: ValueKey(whateverId), // Either the id or a constant
          stackedRoutes: [
            VPopHandler(
              onSystemPop: (vRedirector) async => vRedirector.push('/two/$whateverId'),
              stackedRoutes: [
                VWidget(
                  path: "/three",
                  widget: View3(),
                ),
              ],
            ),
          ],
        ),
      ],
    ),
  ],
)
```

Two things here:
* The `VPopHandler` allows you to redirect to the right path
* The key is here to ensure that the transition is displayed properly. This is a limitation of `MaterialPage`. If you plan on having a 'user/id' -> 'user/anotherId' transition, the key should be the id. Otherwise you can just use a constant in `ValueKey` and this will work when popping.

This is the best solution if you want to keep the same paths that you have. The only limitation is that if you want a 'user/id' -> 'user/anotherId' transition AND you don't have the id BEFORE popping from `/three`, this is not possible. 

I hope this helps! If you want to understand the limitations about keys I can tell you more about them but just know that those limitation can not be avoided.

**Comment by satvikreddy** [comment]
Thank you very much for the quick response!!

I tried using the first solution (using relative path).
Pressing back button on View3 still closes the app on android.

My use case is both for web and android so I would like it to work in both. Am I missing something?

Thanks in advance.

**Comment by lulupointu** [comment]
Ok this is unexpected, I will investigate and come back to you. Thanks for the thorough issue description.

**Comment by lulupointu** [comment]
Fixed. I will just take the opportunity to ship migration precision in the README but this should be pushed in v1.1.0+14 in a few minutes.

**Comment by lulupointu** [comment]
Done.
Do not hesitate to reopen if this did not work for you.

**Comment by satvikreddy** [comment]
Thanks a lot for the quick fix 👍 
Works now.
