### ISSUE TITLE
Unable to pass params directly to view

### ISSUE THREAD

**Issue by esDotDev** [lulupointu/vrouter#36]
One use case I would really like to do with a library like this, is to parse params directly in the routing table, kind of like we used to do with onGenerateRoute.  This way the view doesn't have to parse, it is just cleanly passed it's dependencies.
```
VWidget(
  path: "/product/:id",
  widget: ProductPage(
    pageId: getRouter()?.pathParameters["id"],
  ),
)
```

I can't seem to find a nice way to do this currently? Even if I inject it into a shared model, there are still some issues:
* onBeforeUpdate - Seems to be no access to the new path params here, so no way to parse the id.
* onAfterUpdate - View has already built by now (initState has fired)
* inline (as above) - Params are always old

A couple of things that could help is:
* VWidgetBuilder(builder: (params){ }) - We can parse things here, and inject straight into the views
* onBeforeUpdate(_, newParams) - Pass the new params into the update, so we can inject them into a model if we need _before_ the view has rendered.

The main reason for this is separation of concerns. If Pages can depend on constructor injection they are easier to test and simpler to understand. I also appreciate how it keeps the parsing close to the declaration ("id" is 2 lines away from ":id"). 

I think the builder in particular is quite nice. It removes the boilerplate around assigning a key in order to access the params from the routing tree, and just passes the new params directly.
```
VWidget(
  path: "/product/:id",
  widgetBuilder: (params) => ProductPage(pageId: params["id"]),
)
```

**Comment by esDotDev** [comment]
In the README, it shows some example like:
```
class UserScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final id = context.vRouter.pathParameters['id'];
  }
}
```

But what I would prefer to do is something more like:
```
class UserScreen extends StatelessWidget {
  UserScreen({required String userId})
  final int userId;
  
  @override
  Widget build(BuildContext context) { }
}
```
In the former it has a hidden dependency that is not visible externally (and actually quite tricky to mock). In the latter, the contract is clear, anyone can instantiate this widget and know what they must provide it, and we can inject any arbitrary id for testing purposes.

**Comment by lulupointu** [comment]
I understand what you mean I was myself in this situation many times.

What I did is use a `Builder` widget, have a look at [here](https://github.com/flutter/uxr/blob/317ec6e5799d6732a44b0c313cc2183b9382240a/nav2-usability/scenario-code/deeplink-pathparam/deeplink_pathparam_vrouter.dart#L39).

More generally, if you want to see more advanced navigation scenario I would suggest you look [here](https://github.com/lulupointu/vrouter/issues/13) and for each scenario look at the `vrouter` code. There are not every implementation because my PR is pending but eventually we should get there. 
Also those should be on the website at some point but I would rather have them all done with feedback before.

**Comment by esDotDev** [comment]
Ah, gotcha, well in that case I can make a wrapper for that too :) 

I would consider at the least adding newParams to beforeUpdate, so anyone using a model to hold their params, can avoid the builder, and that should not break anything.

I understand the issues around having both a .child and a .builder, I'm not sure it's reason enough to completely bail on builders because the use-case here is so strong, but I totally get the ambiguity it added to the API. 

imo, the best approach would be to not worry too much about "_allow only widgetBuilder: not ideal for those who don't need it_", at the end of the day they need to do `builder: () => MyChild` instead of `child: MyChild()` which seems hardly worth the optimization of taking a child.

Anyways, thanks for the quick response and solution :)

**Comment by lulupointu** [comment]
I agree that this would not be much but also having `Builder((context) => MyChild())` instead of `(context) => MyChild()` is not a big deal :grin:

In `beforeUpdate` you do have the path parameters though with `vRedirector.newVRouterData.pathParameters` or `vRedirector.newVRouterData.queryParameters`

**Comment by esDotDev** [comment]
> I agree that this would not be much but also having `Builder((context) => MyChild())` instead of `(context) => MyChild()` is not a big deal 😁

:D Fair! 

> In `beforeUpdate` you do have the path parameters though with `vRedirector.newVRouterData.pathParameters` or `vRedirector.newVRouterData.queryParameters`

Ahh I see, ty!

**Comment by esDotDev** [comment]
Just to loop back, using the Builder simplifies a lot. I can avoid the per-route VGuard now so the whole tree is much more readable, and the Stack makes a lot more sense.

No one would be confused if you added: `VWidget.builder(Widget Function(params) builder, ...)` just sayin :)

**Comment by esDotDev** [comment]
For anyone who might stumble on this, I came up with thiis little helper method for now:
```
// A small wrapper so we can make routing table more readable.
VRouteElement _VRoute({
  required String path,
  required Widget Function(Map<String, String> pathParams, Map<String, String> queryParams) builder,
  List<String>? aliases,
  Future<void> Function(VRedirector vRedirector)? beforeEnter,
}) {
  return VGuard(
    beforeEnter: beforeEnter ?? (_) async {},
    stackedRoutes: [
      VWidget(
        aliases: aliases ?? [],
        path: path,
        widget: Builder(
          builder: (context) {
            Map<String, String> pathParams = VRouter.of(context).pathParameters;
            Map<String, String> queryParams = VRouter.of(context).queryParameters;
            return builder(pathParams, queryParams);
          },
        ),
      ),
    ],
  );
}
```

Which, in usage will let you write a much more condensed tree, and provide whatever combination of params you need: 
```
routes: [
  _VRoute(
    path: HomePage.path,
    builder: (_, __) => HomePage(),
  ),
  _VRoute(
    path: SearchPage.path + "/:tab",
    aliases: [SearchPage.path],
    builder: (pathParams, __) {
      SearchPageTabType tabType = searchPageTabTypeFromString(pathParams["tab"]);  //Parse string to enum
      return SearchPage(tabType: tabType); // Pass enum to page
    },
  ),
```

**Comment by Techno-Disaster** [comment]
@lulupointu small question, is it possible to send data between pages but not in path params or query params, something like settings.arguments in navigator 1.0

**Comment by lulupointu** [comment]
It's not possible but it's wanted. 

The issue with what you are asking is that if this is possible if will be easy to have a view which expects an argument. This is not an issue on mobile but is on the web, since on the web anyone can type any url, and when a url is typed there will be no `settings.arguments`, likely causing some issue.

In any case you can find other way to achieve what you want. The best one is to use the pathParameters or queryParameters to an id value, and retrieve the object from your app state using this id. You might argue that this is no different than `settings.arguments` but it is because it makes you very aware that you are relying on the `url` instead of providing you with some magical `arguments` which could crash in cases you don't think of.

**Comment by Techno-Disaster** [comment]
> It's not possible but it's wanted.
> 
> The issue with what you are asking is that if this is possible if will be easy to have a view which expects an argument. This is not an issue on mobile but is on the web, since on the web anyone can type any url, and when a url is typed there will be no `settings.arguments`, likely causing some issue.
> 
> In any case you can find other way to achieve what you want. The best one is to use the pathParameters or queryParameters to an id value, and retrieve the object from your app state using this id. You might argue that this is no different than `settings.arguments` but it is because it makes you very aware that you are relying on the `url` instead of providing you with some magical `arguments` which could crash in cases you don't think of.

@lulupointu How would you suggest to pass an object in path/query params? I'm not sure what you mean by getting these from the AppState. Is there any example with this? That would be really great. Thanks!!

**Comment by lulupointu** [comment]
Here is one example of what I am talking about: https://github.com/flutter/uxr/blob/master/nav2-usability/scenario_code/lib/deeplink-pathparam/deeplink_pathparam_vrouter.dart

Here the state (ie `books` is in a widget) but it could be put in a provider or some other state management thing

**Comment by Techno-Disaster** [comment]
> Here is one example of what I am talking about: https://github.com/flutter/uxr/blob/master/nav2-usability/scenario_code/lib/deeplink-pathparam/deeplink_pathparam_vrouter.dart
> 
> Here the state (ie `books` is in a widget) but it could be put in a provider or some other state management thing

Thanks, I decided to remove all the "objects" passed into different pages and now I'm sending some sort of id and getting the again on the other page

**Comment by lulupointu** [comment]
> Thanks, I decided to remove all the "objects" passed into different pages and now I'm sending some sort of id and getting the again on the other page.

Great this is what you should do!

> Also I noticed that the docs don't really tell the difference between stackedroutes and nestedroutes, could you add that ? Thanks again

`stackedRoutes` is used to stacke widget on top of each other. 

`nestedRoutes` provides a way to nest instead of stack.

Note that this is only relevant from the `Widget` point of view. From the point of view of `VRouteElement`s both are the same (meaning that `VGuard` for examples behaves the same)

**Comment by Techno-Disaster** [comment]
> > Thanks, I decided to remove all the "objects" passed into different pages and now I'm sending some sort of id and getting the again on the other page.
> 
> Great this is what you should do!
> 
> > Also I noticed that the docs don't really tell the difference between stackedroutes and nestedroutes, could you add that ? Thanks again
> 
> `stackedRoutes` is used to stacke widget on top of each other.
> 
> `nestedRoutes` provides a way to nest instead of stack.
> 
> Note that this is only relevant from the `Widget` point of view. From the point of view of `VRouteElement`s both are the same (meaning that `VGuard` for examples behaves the same)

Hey thanks, I got nest vs stack by the description, but what exactly does nest mean? By stack I assume the pages go on top of one another, so how does nesting work?

**Comment by lulupointu** [comment]
You are right about stack.

For nest, you will notice that you have a `widgetBuilder` argument in `VNester` (instead of the `widget` argument of `VWidget`). This `widgetBuilder` gives you a child, which is the widget (or the stack of widgets) of the matching `nestedRoute`. You can therefore use `widgetBuilder` to nest a widget inside another. Here is an example of this: https://vrouter.dev/guide/Examples/Nesting
Also you have another explaination of nesting here: https://vrouter.dev/guide/Essentials/Widget%20nesting

**Comment by Techno-Disaster** [comment]
> You are right about stack.
> 
> For nest, you will notice that you have a `widgetBuilder` argument in `VNester` (instead of the `widget` argument of `VWidget`). This `widgetBuilder` gives you a child, which is the widget (or the stack of widgets) of the matching `nestedRoute`. You can therefore use `widgetBuilder` to nest a widget inside another. Here is an example of this: https://vrouter.dev/guide/Examples/Nesting
> Also you have another explaination of nesting here: https://vrouter.dev/guide/Essentials/Widget%20nesting

Ah okay, that makes sense. Thanks for the quick replies. One last small question, is there a example for handling alertboxes, model sheets and other showX stuff? 

I'm currently following [this](https://github.com/lulupointu/vrouter/issues/63#issuecomment-844838998) , maybe add this to the docs because showX stuff is pretty common in all apps?

**Comment by lulupointu** [comment]
You are following the right issue for this topic. As you see in the end the classic `showX` does work now. Also why I describe in the comment you sent is still the recommended way.

I am not posting this because I plan on pushing theses `Pages` to the flutter repo. I have began to work on this but I don't have much time atm. Anyway once it will be done anyone will be able to have them from flutter directly !

**Comment by Techno-Disaster** [comment]
@lulupointu what about for stuff like `popUntilIsFirst`? If I'm not wrong, with `pushReplacement` only the current page is popped and new one is added, is there any way for `popUntilIsFirst` or `removeAllOthersAndPush`

**Comment by lulupointu** [comment]
Here is an issue about just that https://github.com/lulupointu/vrouter/issues/75 😉

**Comment by Techno-Disaster** [comment]
> Here is an issue about just that #75

Ah thanks, I should have checked the issues first. I came up with another issues, is there any way to completely remove transitions? I was trying to follow [this](https://flutter.dev/docs/release/breaking-changes/route-transition-record-and-transition-delegate) but looks like I can't do that in vrouter

**Comment by Techno-Disaster** [comment]
> > Here is an issue about just that #75
> 
> Ah thanks, I should have checked the issues first. I came up with another issues, is there any way to completely remove transitions? I was trying to follow [this](https://flutter.dev/docs/release/breaking-changes/route-transition-record-and-transition-delegate) but looks like I can't do that in vrouter

Looks like adding ` buildTransition: (x, y, child) => child,` to VRouter did it

**Comment by lulupointu** [comment]
> Looks like adding buildTransition: (x, y, child) => child, to VRouter did it

This is indeed the way to achieve what you want 👍
