### ISSUE TITLE
Is there a method similar to Navigator.canPop() ?

### ISSUE THREAD

**Issue by Varunml3** [lulupointu/vrouter#37]
I'm using VNester for my scaffold and I want the appbar in the scaffold to have a custom back button when in a navigation stack. Is there any way I can make it work without canPop() ?

**Comment by lulupointu** [comment]
I don't know your use case but I see several solutions:
1. use `Navigator.canPop` (non-tested)
2. use `VPopHandler`
3. use a custom AppBar BackButton

### 1.use `Navigator.canPop` (non-tested)

No explanations needed, I just don't know if this would work in your case since `VNester` nest a navigator so you might pick the wrong one when using `Navigator.canPop` (it depends on your `context`)

### 2. use `VPopHandler`

This is useful but might not be adapted to your case, whenever the `VPopHandler` is in the current stack, it is called when you pop to you could use it like this:

```dart
VRouter(
  routes: [
    VPopHandler(
      onPop: (vRedirector) async => vRedirector.push('/whereverYouWant'),
      stackedRoutes: [
        VNester(
          path: null,
          widgetBuilder: (child) => MyScaffold(child: child),
          nestedRoutes: [
            VWidget(path: '/user', widget: UserScreen()),
            VWidget(path: '/settings', widget: SettingsScreen()),
          ],
        )
      ],
    ),
  ],
)
```

### 3. use a custom AppBar BackButton

This might actually be the best solution since contrary to solution (2), this would not pollute every pop event:

```dart
Scaffold(
  appBar: AppBar(
    leading: BackButton(
      onPressed: () => context.vRouter.push('/whereverYouWant'),
    ),
  ),
  body: child,
)
```

**Comment by Varunml3** [comment]
Ok thanks for the advice
I really love the package so keep it up 😄
