### ISSUE TITLE
Parent page is visible for very short time when jumping to nested page

### ISSUE THREAD

**Issue by mordivgor** [lulupointu/vrouter#41]
Hi,

I have noticed that there is some problem with jumping to nested page. Everything works properly, but when I am jumping to nested page, then parent page is being built and visible for very short time.

It is almost impossible to see this in simple widgets, but in case of complex pages (which needs a little more time to be loaded) it is visible. Because of a need of short reproducible code, below one shows only that "prints" happened - when I am jumping to nested page, there is an execution of "build" method of parent page.
In case of not nested pages ("other" in below example) - problem is not visible.

```
import 'package:flutter/material.dart';
import 'package:vrouter/vrouter.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return VRouter(
      builder: (BuildContext context, Widget child) {
        return Scaffold(
          body: child,
        );
      },
      routes: [
        VWidget(
          path: '/',
          widget: ParentPage(),
          stackedRoutes: [
            VWidget(
              path: 'nested',
              widget: NestedPage()
            ),
          ]
        ),
        VWidget(
          path: '/other',
          widget: OtherPage()
        )
      ],
    );
  }
}

class ParentPage extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    print('building parent page');
    return Row(
      children: [
        RaisedButton(
          child: Text('Go to nested page'),
          onPressed: () => VRouter.of(context).push('/nested'),
        ),
        RaisedButton(
          child: Text('Go to other page'),
          onPressed: () => VRouter.of(context).push('/other'),
        )
      ],
    );
  }
}

class NestedPage extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    print('building nested page');
    return RaisedButton(
      child: Text('Go to parent page'),
      onPressed: () => VRouter.of(context).push('/'),
    );
  }
}

class OtherPage extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    print('building other page');
    return RaisedButton(
      child: Text('Go to parent page'),
      onPressed: () => VRouter.of(context).push('/'),
    );
  }
}

```

**Comment by lulupointu** [comment]
I want to be sure that I understand you issue so let me try to rephrase it: when building stacked pages, the lower one is visible for a small period of time.

If what you say is true (and it would not surprise me), this is an "issue" with flutter rather than `VRouter`. 

When `vrouter` tries to build the path `/nested` for the following configuration:
```dart
VWidget(
  path: '/',
  widget: ParentPage(),
  stackedRoutes: [
    VWidget(
      path: 'nested',
      widget: NestedPage()
    ),
  ]
),
```

it translate it into the following:
```dart
Navigator:
  pages: [
    MaterialPage(child: ParentPage()),
    MaterialPage(child: NestedPage()),
  ]
),
```

So indeed `ParentPage` is built, and `NestedPage` on top of it, this is how `Navigator` works.

I am therefore not surprised that, if the `ParentPage` takes a lot of time to build, it might be visible before `NestedPage`.
The ideal would be to be able to test this with a widget which does take a lot of time to build, then test with `vrouter` and the vanilla `Navigator` API. I will try to do this.
If it comes from `VRouter`, I will investigate further.
If it does not, I won't. You might bring this to the flutter team to hear what they have to say if it's an issue with vanilla Navigator. But I am sure they will say that build methods have to be pure and should not do a tone of work, which yours might.

Anyway I will come back to you if I can reproduce the behavior you are reporting. In the meantime, I will advice the same as the Flutter team does: find which build method is doing to much work and try not to do this much work here.

**Comment by mordivgor** [comment]
Thank you for very comprehensive answer.
Indeed, when you show how it is being translated sounds like problem with Navigator itself :/
I could raise it to the flutter team, but I am completely lost with this new Navigator 2.0 way of working. If you would be able to translate my code to Navigator usage (not VRouter) then for sure I would raise it (of course, if you would not like to do it).

Anyway, I believe that complex applications have tons of widgets, so build method of whole page might take a while, so for sure I will try to indicate it to the Flutter team.

**Comment by lulupointu** [comment]
Ok so it appears that I was wrong. What I found out is:
1. Flutter is smart
2. I can't reproduce you issue

Even if, as I expected, if you go from `other` to `nested`, then `ParentPage` is built THEN `NestedPage` is built, I don't think this is an issue, since **the widgets are displayed after both build complete**.

I made a small example, based on the one you gave, to show this:

```dart
import 'package:flutter/material.dart';
import 'package:vrouter/vrouter.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return VRouter(
      builder: (BuildContext context, Widget? child) {
        return Scaffold(
          body: child!,
        );
      },
      routes: [
        VWidget(path: '/', widget: ParentPage(), stackedRoutes: [
          VWidget(path: 'nested', widget: NestedPage()),
        ]),
        VWidget(path: '/other', widget: OtherPage())
      ],
    );
  }
}

class ParentPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    print('building parent page');

    for (var _ in List.generate(30000000, (index) => index)) {
      var a = Container();
    }
    return Row(
      children: [
        RaisedButton(
          child: Text('Go to nested page'),
          onPressed: () => VRouter.of(context).push('/nested'),
        ),
        RaisedButton(
          child: Text('Go to other page'),
          onPressed: () => VRouter.of(context).push('/other'),
        )
      ],
    );
  }
}

class NestedPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    print('building nested page');

    for (var _ in List.generate(30000000, (index) => index)) {
      var a = Container();
    }
    return RaisedButton(
      child: Text('Go to parent page'),
      onPressed: () => VRouter.of(context).push('/'),
    );
  }
}

class OtherPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    print('building other page');
    return RaisedButton(
      child: Text('Go to nested page'),
      onPressed: () => VRouter.of(context).push('/nested'),
    );
  }
}
```

**Step to reproduce**:
1. Launch the app
2. Click `Go to other page`
3. Click `Go to nested page`

**On step 3 you will notice**:
1. `building parent page` is printed
2. `building nested page` is printed
3. THEN `NestedPage` appears on the screen, without us seeing `ParentPage`

These 3 steps can easily be observed since I made the `build` methods really long to execute.

This proves that:
1. Flutter is smart
2. I can't reproduce you issue, since it appears not to be linked with `build` execution time as we thought

I am therefore really curious of your issue, could it be that you are calling `context.vRouter.push("/nested")` within the build method of the `ParentPage`? Or in `VGuard.afterEnter`?

**Comment by mordivgor** [comment]
Hello,

Sorry for late response.
I think I have finally reproduce it - looks like problematic part is connected to removal of animated transtion.
I have just added:
```
buildTransition: (animation, _, child) {
        return child;
      },
```
to VRouter and this is my result:

https://user-images.githubusercontent.com/54472480/114735110-2987c500-9d45-11eb-82ee-d2334a827578.mp4

Full code
<details>

```

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:vrouter/vrouter.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return VRouter(
      buildTransition: (animation, _, child) {
        return child;
      },
      builder: (BuildContext context, Widget child) {
        return Scaffold(
          body: child,
        );
      },
      routes: [
        VWidget(
          path: '/',
          widget: ParentPage(),
          stackedRoutes: [
            VWidget(
              path: 'nested',
              widget: NestedPage()
            ),
          ]
        ),
        VWidget(
          path: '/other',
          widget: OtherPage()
        )
      ],
    );
  }
}

class ParentPage extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    print('building parent page');
    List<Widget> _widgets = [];
    for (int i = 0; i < 20; i++) {
      if (i % 2 == 0) {
        _widgets.add(
          Container(
            height: 20,
            color: Colors.red
          ),
        );
      } else {
        _widgets.add(
          Container(
            height: 20,
            color: Colors.transparent,
          )
        );
      }
    }
    return Column(
      children: <Widget>[
        Row(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            RaisedButton(
              child: Text('Go to nested page'),
              onPressed: () => VRouter.of(context).push('/nested'),
            ),
            RaisedButton(
              child: Text('Go to other page'),
              onPressed: () => VRouter.of(context).push('/other'),
            )
          ],
        )
      ] + _widgets
    );
  }
}

class NestedPage extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return Column(
      children: <Widget>[
        RaisedButton(
          child: Text('Go to parent page'),
          onPressed: () => VRouter.of(context).push('/'),
        )
      ]
    );
  }
}

class OtherPage extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return Column(
      children: <Widget>[
        RaisedButton(
          child: Text('Go to nested page'),
          onPressed: () => VRouter.of(context).push('/nested'),
        )
      ]
    );
  }
}

```

</details>

**Comment by lulupointu** [comment]
Oh this makes sense.

I would suggest you change:
```dart
buildTransition: (animation, _, child) {
  return child;
},
```

**changed to:**
```dart
buildTransition: (animation, _, child) {
  return Material(color: Colors.white, child: child);
},
```

What you were worries about is not an error actually this is the default behavior of a `PageTransitionBuilder` if you just return the child.

**Comment by mordivgor** [comment]
Thank you so much for this tip!
It works like a charm :)
