### ISSUE TITLE
Alternative architecture thoughts

### ISSUE THREAD

**Issue by esDotDev** [lulupointu/vrouter#42]
Curious if you've thought of a more page-centric architecture, which would group the page-specific logic with the Page, or at least outside the Router, and then the router is just concerned with declaring the structure of the tree and menu/scaffold nesting.

**The main idea here is separating layout and structure, from data and logic.** Parsing logic, guard logic, and the actual path are grouped together, the tree is then freed to more expressively show layout. 

This is mostly just some food for thought, feel free to close if not interesting :) I've been playing with my own demos, it's becoming clear that you can kinda separate out page-specific behavior, and route management fairly cleanly.

So for example, you might have a VRouteConfig class:
```dart
class VRouteConfig {  required String path; required WidgetBuilder builder; VRouteGuard guard; }

class HomePage extends StatelessWidget {

static final routeConfig = VRouteConfig(
   path: "/home" 
   builder(params) => HomePage(tabIndex: int.tryParse(params[tab]) ?? 0);
   guard: VRouteGuard(onBefore: ... )   // optional
);
```
The routing table could then be simplified and made more readable. The `VRoute` can also offer a `.guard` property to override the one declared with the page, but for the most part pages declare their own guards (as is common in html). 
```dart
/// The router focuses entirely on expressing string mappings : route bindings and wrapping any nested widgets that are required. 
VRouter(
  builder: (_, page) => page; // Can wrap entire app in scaffold/menus
  routes: [
     VRoute(HomePage.routeConfig),
     VRoute(SearchPage.routeConfig, 
         builder: (_, subPage) => subPage; // could have another nested tab menu here
         children: [
             VRoute(SearchPage.routeConfig), //search
             VRoute(SearchExplorePage.routeConfig), //search/explore
             VRoute(SearchRecentPage.routeConfig), //search/recent
             VRoute(SearchNewsPage.routeConfig), //search/news
         ]
     ),
  ]
)
```
Or alternatively, you could declare them all as vars at the high level, then and put it all together in the router:
```dart
final homeRoute = RouteConfig(
   path: "/home" 
   builder(params) => Home(int.tryParse(params[tab]) ?? 0);
);

final searchRoute = RouteConfig(
   path: "/search" 
   builder(params) => SeachPage(query: params[query]));
);

final searchRouteExplore = RouteConfig(
   path: "/search/explore" 
   builder(params) => SeachPage(query: params[query], selectedTab: SearchType.explore));
);

return VRouter(
  builder: (_, page) => page; // Can wrap entire app in scaffold/menus
  routes: [
     VRoute(homeRoute),
     VRoute(searchRoute, 
         builder: (_, subPage) => subPage; // could have another nested tab menu here
         children: [
             VRoute(searchRoute), //search
             VRoute(searchRouteExplore ), //search/explore
             ... etc
```

Another variation of this would be to declare static methods for these configs, which is kind of interesting, so we could get different flavors, or override guards externally.
```dart
VRoute(SearchPage.getRouteConfig(guard: ...))); // Could override the default guard 
// or maybe use a pre-made one that the page defines
VRoute(SearchPage.protectedRouteConfig); 
```
Of course these are all implementation details that the router would not be concerned with. It doesn't care how it gets its route configs, just that it gets them. These examples are just to show the nice things you could do when we decouple at this pt.

**Comment by esDotDev** [comment]
Another interesting side effect you'd get here is really easy linking. The router could go through all PageConfig objects, and inject the the navigator. 

Then you could have `onPressed: () => SearchPage.route.push()`

Internally PageConfig is just doing something like => `_router.setPath(this.path)`

**Comment by lulupointu** [comment]
Hi, thanks for taking the time to experiment and to report here what you have learned.

Concerning what you are saying, I think I see 2 main concerns:
1. Having a `VContainer` (a `VRouteElement` which has every configuration in it, compared to specialized `VRouteElement`)
2. How to extract the logic from `VRouter` in order not to have what can become a huge configuration inside it

If I am missing a concern please express it explicitly in response. 

In any case, I will response to (1) and (2) above.

### Concerning (1) AND (2)
I would like to have a `VRouteElement`, that you can extends, as you do with a `StatelessWidget`, which would allow you to do thing like:

```dart
class VContainer extends VRouteElement {
  final String path;
  final Widget Function(BuildContext) builder;
  final Future<void> Function(VRedirector) beforeEnter;

  VContainer({
    required this.path,
    required this.builder,
    required this.beforeEnter,
  });

  List<VRouteElement> get subRoutes => [
        VGuard(
          beforeEnter: beforeEnter,
          stackedRoutes: [
            VWidget(
              path: path,
              widget: Builder(
                builder: (context) => builder(context),
              ),
            ),
          ],
        )
      ];
}
```

but also (and more interestingly IMO):

```dart
// Reusable VRouteElement
class AuthenticationGuard extends VRouteElement {
  final BuildContext context;
  final VRouteElement subRoute;

  AuthenticationGuard({required this.context, required this.subRoute});

  List<VRouteElement> get subRoutes => [
        VGuard(
          beforeEnter: (vRedirector) async {
            if (!context.read<AuthenticationState>().isConnected) vRedirector.push('/login');
          },
          stackedRoutes: [subRoute],
        )
      ];
}


// VRouteElements corresponding to different routes

class LoginRoute extends VRouteElement {
  List<VRouteElement> get subRoutes => [VWidget(path: '/login', widget: LoginScreen())];
}

class HomeRoute extends VRouteElement {
  final BuildContext context;

  HomeRoute(this.context);

  List<VRouteElement> get subRoutes => [
        AuthenticationGuard(
          context: context,
          subRoute: VWidget(path: '/login', widget: LoginScreen()),
        )
      ];
}
```

which could then be used like so:

```dart
// Much simpler to read configuration
VRouter(
  routes: [
    LoginRoute(),
    HomeRoute(context),
  ],
)
```

This are simple examples but you could can imagine that some things become really easy:
* Create a reusable, custom `VRouteElement`s
* Creating a `VRouteElement` corresponding to each of you app parts, breaking your route structure into independent, easy to manage bloc

### Concerning (1): Having a `VContainer` (a `VRouteElement` which has every configuration in it, compared to specialized `VRouteElement`)

We have discussed this issue before, the idea of a `VContainer` is not attractive to me, but:
1. This could change as we discussed, I am still wanting for the user study result
2. This could be easily done by the architecture proposed above

### Concerning (2): How to extract the logic from `VRouter` in order not to have what can become a huge configuration inside it

This point is a major focus. Right now `VRouter` is kind of lacking in this domain (I honestly don't know how other packages perform in this domain, I am just not happy with `VRouter` at this point).

What is proposed above would be a first step towards this. However it is not enough, since it would solve the issue of the router configuration but not the issue of the navigation which is still kinda hard into a large application, remembering all these paths.

The solutions I envision can be found [here](https://github.com/lulupointu/vrouter/tree/nested), though it's not really detailed right know because I don't have much time atm. However the two main ideas are:
1. Allowing `VRouter` nesting, with each `VRouter` having a `basePath` based on where you place it. All `Screen` inside this `VRouter` will navigate using path relative to the `basePath`, which means that using them in isolation or within another `VRouter` would not require any change (navigation-wise).
2. Navigating by type, which is the same as named navigation really, but could have some interesting benefits, I still need a lot of thought there to make things right

But point 1 could really answer your issue of separation of concern I think, it's just a complex issue which needs many more though-time that I have right now.

Anyway, tell me what you think, if I completly missed your/one of your point tell me as well! I'm always glad to discuss even if we don't always agree!

**Comment by lulupointu** [comment]
> Another interesting side effect you'd get here is really easy linking. The router could go through all PageConfig objects, and inject the the navigator.
> 
> Then you could have `onPressed: () => SearchPage.routeConfig.push()`
> 
> Internally PageConfig is just doing something like => `_router.setPath(this.path)`

This kind of things can already be achieved by using named navigation I think. Using static fields to contain those name is already possible, though it might be easier to attach those to the `VRouteElement` mentioned above like so: 

```dart
class LoginRoute extends VRouteElement {
  static String name = 'loginRoute';
  List<VRouteElement> get subRoutes => [VWidget(path: '/login', widget: LoginScreen(), name: LoginRoute.name)];
}
```

and then navigate using:
```dart
context.vRouter.pushNamed(LoginRoute.name)
```

**Comment by lulupointu** [comment]
Any though about this ? Positive/Negative remarks? If not we might close this :+1:

**Comment by esDotDev** [comment]
Ya I think this is ok to close, this discussion inspired me to make my own lib, similar to yours but different as well.
https://pub.dev/packages/nav_stack

I'm able to reproduce your example on the README like:
```
return NavStack(
  stackBuilder: (context, controller) {
    return PathStack(
      scaffoldBuilder: (_, stack) => _MyScaffold(stack),
      routes: {
        ["/login", "/"]: LoginScreen().buildStackRoute(),
        ["/in/"]: PathStack(
          routes: {
            ["profile/:profileId"]:
                StackRouteBuilder(builder: (_, args) => ProfileScreen(profileId: args["profileId"] ?? "")),
            ["settings"]: SettingsScreen().buildStackRoute(),
          },
        ).buildStackRoute(onBeforeEnter: (_) {
          if (!isLoggedIn) controller.redirect("/login", () => showAuthWarning(context));
          return isLoggedIn; // If we return false, the route will not be entered.
        }),
      },
    );
  },
);
```

Thanks a lot for the discussion and inspiration!
