### ISSUE TITLE
As Vrouter uses material app styles are broken for cupertino native widgets

### ISSUE THREAD

**Issue by sergeylappo** [lulupointu/vrouter#51]
Hello, I was really intrigued by your library and tried to integrate it into my project.

I'm also using https://pub.dev/packages/flutter_platform_widgets library to deliver native experience.

On web/android everything looks perfect, but as as far as I understand, as long as VRouter/VMaterialApp reuses Material app - styles for native widgets on Mac OS seems to be broken (text should have default platform styling).
![image](https://user-images.githubusercontent.com/9092362/115990777-c829e680-a5cd-11eb-98e3-a3c77feb8708.png)

Maybe you have ideas on how to fix this?

**Comment by lulupointu** [comment]
Hi, could you tell me if using `MaterialApp` instead of `CuperinoApp` in a very simple app (like a centered text) does the same thing?

**Comment by lulupointu** [comment]
Mmmm, from what I see in https://pub.dev/packages/flutter_platform_widgets, you should use PlatformApp, which you can't since you use VRouter. However what I mentionned above (using `CuperinoApp` or `MaterialApp` depending on the platform would do the trick), it would mean 1 manual check for you but I guess that's ok.I'll add this option in the next release and let you know, this should not take more than a week (since I'm currently working on refactoring).

**Comment by lulupointu** [comment]
Fixed in `v1.1.1+1`

You can now use the following:
```dart
PlatformApp.router(
    routeInformationParser: VRouteInformationParser(),
    routerDelegate: VRouterDelegate(routes: [...]),
    backButtonDispatcher: VBackButtonDispatcher(),
  );
```

**Comment by sergeylappo** [comment]
Sorry for not replying, was a bit over-loaded for the last 3 days.

Thanks for such a quick fix! Would test it now!

**Comment by lulupointu** [comment]
No worries I just pushed the update! 😉

**Comment by sergeylappo** [comment]
Thanks! Seems to be working really well!

Would finish my migration and continue development.
For now looks really promising!
