### ISSUE TITLE
Setting Global Key for Multiple Navigators

### ISSUE THREAD

**Issue by princestha** [lulupointu/vrouter#6]
Just to start off, I am very impressed with this package. Finally, an easy way to add nesting. Great work. Thank you

I was just experimenting and was wondering, is it possible to have multiple VRouters? **Although I don't think I need this since there is nesting available, I was just wondering if it is possible. Possibly to manually control the routes. 

I tried to set my own Navigator key 
`GlobalKey<NavigatorState> _first =
      GlobalKey<NavigatorState>(debugLabel: 'first');
  GlobalKey<NavigatorState> _second =
      GlobalKey<NavigatorState>(debugLabel: 'seconds');`
But I am getting an error. 
`The following assertion was thrown while finalizing the widget tree:
Duplicate GlobalKey detected in widget tree.

The following GlobalKey was specified multiple times in the widget tree. This will lead to parts of the widget tree being truncated unexpectedly, because the second time a key is seen, the previous instance is moved to the new location. The key was:
- [LabeledGlobalKey<NavigatorState>#4d2f8]`

Thank you

**Comment by lulupointu** [comment]
Thanks! Since nesting is so present in flutter it was something very important to me. I'm glad it helps! 

You get this error when using multiple VRouter? If so it does not surprise me since this is not supported.
It might be supported as a VRouteElement to make it easier for people working in large teams but never nesting inside widget (this is because every routes has to be known from the start of the app)

**Comment by lulupointu** [comment]
I just saw you comment on YouTube. Can you provide a small example of what you are trying to achieve so that I can help you?
