### ISSUE TITLE
What is the point of VMaterialApp?

### ISSUE THREAD

**Issue by esDotDev** [lulupointu/vrouter#72]
I'm curious what the use cases are for this Widget? It seems like VRouter proxies through all of the properties, so why would we ever need to use VMaterialApp?

**Comment by lulupointu** [comment]
If you need a nested `MaterialApp` then use `VMaterialApp`.

This is because mixing `MaterialApp` and `MaterialApp.router` (the later is the one used by `VRouter`, which is needed for url reporting) messes with url reporting. At least it used to, there is an open issue on the flutter repo about this, they wanted to solve it but in the meantime I provide the solution)

**Comment by esDotDev** [comment]
Ya, I was just wondering why anyone would actually need multiple Material Apps...  if there are some common use cases for it or something I am missing.

**Comment by lulupointu** [comment]
Not that I see, but I think I had someone open an issue here about that. Maybe someone who wants a different theme and doesn't know Theme exists as a widget? idk tbh ^^

**Comment by esDotDev** [comment]
Also, fwiw, we did burn some time on this, as we saw `VRouter` and `VMaterialApp` and thought to needed to use both, then got confused when theme wasn't working! 

Noob mistake, but might be worth calling out in the docs or something...
