### ISSUE TITLE
What problems are the `stackedRoutes` and `nestedRoutes` trying to tackle?

### ISSUE THREAD

**Issue by johnwangwjq** [lulupointu/vrouter#76]
Sorry for this question not being specific to `vrouter` but a general one.  I'm using vrouter and new to flutter stuff so here I come ;-b. 

The [document](https://vrouter.dev/guide/Essentials/Route%20formation)  by itself is clear on the *how*, but not the *why*, ie., why do we need nestedRoutes/stackedRoutes in the first place? what benefits/consequences they give us as oppose to using a flat routes configure? I'm a seasoned traditional(non-SPA) web developer. Simply show the problems they are trying to solve will be enough to help me understand the document.

BTW, I guess there are typos in the end of the above document link, ie.,  
> ...UserWidget will never be visible because for the path '/user', OtherWidget will be displayed...

should be:

> ...UserScreen will never be visible because for the path '/user', OtherScreen will be displayed...

**Comment by lulupointu** [comment]
I would say that there are 2 reasons for `stack/nested routes`:
1. It's more flutter idiomatic
2. It allows for a stack view of the `routes`, which is what is often use in mobile dev
3. Considering 1 and 2 together makes it all the more powerful

### 1. It's more flutter idiomatic

Consider those 2 examples:

*Example 1:*
```dart
VWidget(
  beforeEnter: someFunction(),
  onPop: someOtherFunction(),
  path: '/',
  widget: HomeScren(),
)
```

*Example 2:*
```dart
VGuard(
  beforeEnter: someFunction(),
  stackedRoutes: [
    VPopHandler(
      onPop: someOtherFunction(),
      stackedRoutes: [
        VWidget(
          path: '/',
          widget: HomeScren(),
        ),
      ],
    ),
  ],
)
```

The difference between the two is that in *example 1* you have 1 class which does everything, whereas in *example 2* each class does its thing, and only its thing. It's the same idea that flutter has with its widgets.

If you are new to flutter you might no see the benefit of this, and many newcomers find it ugly or think it does not scale well but I would argue the opposite. You have plenty articles online to know why such a structure is very likable so you can search for this if you are interested.

This explains why `stackedRoutes` exists for `VGuard` and `VPopHandler`, but maybe not why they do for `VWidget` or `VNester`. For this, see my second point. 

### 2. It allows for a stack view of the `routes`, which is what is often use in mobile dev

If you want to put a route on top of another, and they just say "pop back on the route bellow", you have to have an idea of a stack. I'm sure you have seen this in the app you use, and maybe have experience with this if you have ever done mobile dev even on small scale.

This explains why we need `stackedRoutes` in `VWidget`.

Of course if you don't want to stack but want to embed a nested navigation thing, you will use `VNester`, this is often used when some element needs to be static while only a portion of the screen is concerned with route animations/transitions. The typical example is a `Scaffold` with a `BottomNavigationBar`. When tapping the icons of the `BottomNavigationBar`, ONLY the body of the `Scaffold` should perform a route transition.

This is why we need `nestedRoutes` in `VNester`


### 3. Considering 1 and 2 together makes it all the more powerful

Now lets consider 1. and 2 together, and suppose we need this settings:
- Something which checks if the user if authenticated
- A `HomeScreen` to land
- A `SettingsScreen` stacked on top of a `HomeScreen`

Here is how you would implement this:
```dart
VGuard(
  beforeEnter: checkUserAuthenticated(),
  stackedRoutes: [
    VWidget(
      path: '/',
      widget: HomeScren(),
      stackedRoutes: [VWidget(path: 'settings', widget: SettingsScreen())],
    ),
  ],
)
```

Did you notice something marvelous ? 
Here it is: because we use `VGuard`, it makes sense that even if the user would go directly to `SettingsScreen`, `beforeEnter` would be executed. 
Whereas if you used the form we saw in *example 1*, here is what we would have need to be written:

```dart
VWidget(
  beforeEnter: checkUserAuthenticated(),
  path: '/',
  widget: HomeScren(),
  stackedRoutes: [
    VWidget(
      beforeEnter: checkUserAuthenticated(),
      path: 'settings',
      widget: SettingsScreen(),
    ),
  ],
)
```

And in that case, since `HomeScreen` **is** bellow `SettingsScreen`, if we access `SettingsScreen`, will both be executed or only one? Also if you add another route, you need not to forget `beforeEnter`. The more your project grows, the more you start to realize how useful it is to have this separation of concern.

This is what makes Flutter powerful. `VRouter` only applies the same principles to routing :wink: !

**Comment by lulupointu** [comment]
Oh and thanks for the typo, I'll correct this

**Comment by johnwangwjq** [comment]
Thanks for these in-depth explaination. I've felt the sense a bit. Let me close it for now. I need to read this multiple times while getting hands dirty on code to really understand all these stuff.

**Comment by johnwangwjq** [comment]
An useful link for later reading: [how a nested navi behave](https://reactnavigation.org/docs/nesting-navigators/#how-nesting-navigators-affects-the-behaviour)
