### ISSUE TITLE
Is there a way to pass url query parameters apart from the ones in path?

### ISSUE THREAD

**Issue by johnwangwjq** [lulupointu/vrouter#78]
Here are actually two questions:

1. As the issue title said, is there a way to pass query parameters? Eg., instead of  `/users/bob` for path `/users/:userId`, could I use `/users?id=bob`? I guess I could set the path as `/users?id=:userId` for the later, could I?
2. Is this a best practice here that not to use quary string but totally rely on path parameters? If it's I'll love to follow. I know path parameters can meet most requirement. But query string is a convention for those non-strick(chould be ignored by server) parameters. So I guess I would need them in some cases.

**Comment by johnwangwjq** [comment]
Oh there is `queryParameters` property, sorry ;-b

**Comment by lulupointu** [comment]
Hi,

First `/users?id=:userId` -> Is not valid.
Second "But query string is a convention for those non-strick (should be ignored by server)" -> In flutter everything is ignored by the server. Your server sends `main.js` containing your app once (when its open, only looking at the start of the url) and then the server is never questioned again.

Knowing 1 and 2, the question is, **what is path parameters vs query parameters?**

The following describes `VRouter` approach, the last section will describe why this approach has been taken.

## Path parameters

Path parameters are part of the **path** that is described using `VRouteElement.path` (i.e. `VWidget.path`). They are a hard constraint meaning that they must be there to go to the wanted `VWidget`.

This is why `VRouter` has `advanced path parameters` with regexp, so that they can be limited to only numbers (e.g. `r'id:userId(\d+)'`).

## Query parameters

They can be used in any route, with anything, and cannot be constrained. Developed should not expect them to be their but rather expect that they **might** be there and they can do something when they are (scroll to somewhere for example)

## Why are they what they are?

Since there is no difference *per say* (since flutter tells servers to ignore the entire url anyway), `VRouter` chooses to differentiate them so that they both have their strengths and therefore both have their usefulness.

Well you closed it but I'll still send you this now that it's written, maybe it can help you understand anyway !

**Comment by johnwangwjq** [comment]
Yes this is indeed help me on confirming my understanding. Thank you so much for pushing me on the back while I'm learning in the flutter/vrouter land.
