### ISSUE TITLE
Delay when building with VRouter

### ISSUE THREAD

**Issue by esDotDev** [lulupointu/vrouter#83]
I'm seeing nearly a 300ms delay before the builder() is called in VRouter. Any ideas?

Here I trace out  3 times, 
* initState
* initState + scheduleMicrotack (frame 2)
* VRouter.builder

flutter: InitState @ 0
flutter: Frame2 @ 197ms
**flutter: VRouter Build @ 284ms**

**Comment by lulupointu** [comment]
Mmm, I don't know I'll have a look into it. Though I'm not sure I can do something about it ^^

**Comment by esDotDev** [comment]
Ok, I'll try and get a better code example for ya

**Comment by lulupointu** [comment]
I'm waiting for a code example before investigating further but I will.

However I'm not sure why this would be an issue. Maybe could you provide my with a short snippet of what you are trying to accomplish and I can help you ? Without anything I would suggest trying `WidgetsBinding.instance.addPostFrameCallback` instead of `scheduleMicrotack` but maybe is this not right for you.

**Comment by esDotDev** [comment]
Well there's 2 issues that result from this:
1.  A black flicker at app-start, so I have to wrap the entire VRouter in a container to avoid that.
2. If relying on `builder()` to get a context we can use for `showX` pattern, we have to wait more than 1 frame, which is a bit of a hassle.

**Comment by esDotDev** [comment]
This also seems to break integration_test (flutter drive), I have a video to show you, but can't post publically.

**Comment by lulupointu** [comment]
You can come on the discord server and post it there maybe?

**Comment by lulupointu** [comment]
Hey, I did some tests.

Here is the test app:

```dart
import 'package:flutter/material.dart';
import 'package:vrouter/vrouter.dart';

late final DateTime startTime;
late final DateTime buildTime;
late final DateTime builderTime;

bool isBuildTimeSet = false;
bool isBuilderTimeSet = false;

void main() {
  startTime = DateTime.now();
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    if (!isBuildTimeSet) {
      buildTime = DateTime.now();
      isBuildTimeSet = true;
    }

    return VRouter(
      builder: (context, child) {
        if (!isBuilderTimeSet) {
          builderTime = DateTime.now();
          isBuilderTimeSet = true;

          print('Difference between buildTime and startTime: ${(buildTime.millisecondsSinceEpoch - startTime.millisecondsSinceEpoch)}ms');
          print('Difference between builderTime and startTime: ${(builderTime.millisecondsSinceEpoch - startTime.millisecondsSinceEpoch)}ms');
        }

        return child;
      },
      initialUrl: '/',
      routes: [VWidget(path: '/', widget: Center(child: Text('Home')))],
    );
  }
}
```

Here is what I get with:

**`flutter run --debug`**
* Difference between buildTime and startTime: 166ms
* Difference between builderTime and startTime: 329ms

**`hot reload`**
* Difference between buildTime and startTime: 24ms
* Difference between builderTime and startTime: 46ms

**`flutter run --profile`**
* Difference between buildTime and startTime: 24ms
* Difference between builderTime and startTime: 72ms

So I think this as nothing to do with `VRouter`.
`VRouter` used to delay a build frame but no longer does. I don't even remember if the navigator was in it or not but it does not matter anymore.
So if you are using `WidgetsBinding.instance.addPostFrameCallback` you should be confident that you would have the navigator mounted (and therefore its context) available.

Concerning you different remarks:

> A black flicker at app-start, so I have to wrap the entire VRouter in a container to avoid that.

Not sure this can be seen in production, since the app starts so fast

> If relying on builder() to get a context we can use for showX pattern, we have to wait more than 1 frame, which is a bit of a hassle.

This is bad practice and you should use `navigatorKey` (as you know), but even if you would need to use builder for that, I am confident that `WidgetsBinding.instance.addPostFrameCallback` would work.

> This also seems to break integration_test (flutter drive), I have a video to show you, but can't post publically.

I would really like to see this. As I said join the discord server and dm me !
I just tried integration_test with `VRouter` and it seems to work fine though, you can have a look here https://github.com/lulupointu/vrouter/issues/46#issuecomment-855209781

**Comment by esDotDev** [comment]
Thanks, to clarify some of these:

* The black flicker is fairly noticeable on desktop which is where we mainly test
* I wasn't sure that using builder to get the context was bad practice, since `.navigatorKey` was missing I thought maybe this was the way you expected us to do it. Thx for clarifying
* I believe the issues with `integration_test` may have been a bug there, we were doing something like:
```
tester.pumpWidget(MyApp());
tester.pumpAndSettle(Duration(seconds: 1)
```
This actually tells flutter to not draw another frame for 1 seconds, and this delay was causing the `late vRouterContext not initialized` error, switching to something like this fixes it:
```
tester.pumpWidget(MyApp());
tester.pumpAndSettle(); // Let all microtasks finish
tester.pump(Duration(seconds: 1)); // Now wait
```

**Comment by lulupointu** [comment]
Ok so basically the remaining issue is: "The black flicker is fairly noticeable on windows which is where we mainly test"

Does putting a color bellow VRouter is enough or would you want to display a splashscreen or something? If you put `VRouter` in a stack and put a splashscreen bellow would that work? I have an idea on how to provide a splashscreen attribute but I'm not sure it's right because on Android and IOS this would not be displayed directly would it ?

**Comment by esDotDev** [comment]
Ya, we can just wrap it in a container and it's no real problem, but thought you might like to know.

A background color might suffice if the delay is unavoidable? 

I've tested this in a spike and it's definitely there, this flickers black for a couple frames:
```
  runApp(VRouter(
    routes: [
      VWidget(path: "/", widget: Container(color: Colors.red)),
    ],
  ));
```

No flicker here: 
```
runApp(MaterialApp(
    home: Container(color: Colors.red),
  ));
```

**Comment by lulupointu** [comment]
Hi, sorry for the long time to respond, I was actually trying to see what might cause this and I might have found it.
Could you try and tell me if that worked (I'm not setup for desktop apps atm)?

You should take vrouter from git main if you want to try:
```yaml
  vrouter:
    git:
      url: https://github.com/lulupointu/vrouter
      ref: main
```

Let me know how it goes !

**Comment by lulupointu** [comment]
You can now test be using `1.1.4+15`. I pushed it even if this does not fix this because it improves vrouter anyway.

**Comment by esDotDev** [comment]
Hmm, I'm still seeing a black flicker w `1.1.4+15`. I have a bit of time, I'll see if I can get some better info.

**Comment by esDotDev** [comment]
It's really odd, almost like a race condition. When I do a super simple spike I can't reproduce, but when I strip down our more complex example, to the same point, it still happens. I'll re-open if I can find anything better to go on.
