### ISSUE TITLE
Always use Uri.encodeFull() in route path?

### ISSUE THREAD

**Issue by johnwangwjq** [lulupointu/vrouter#86]
Just found out that I can not use chinese in the route path directly. I have to urlencode them before hand. Eg.,
`context.vRouter.push('/页面1')` does not work, but `context.vRouter.push(Uri.encodeFull('/页面1'))` does.

So a small question out of curiosity: Is it a best practice that we always wrap our route path in `Uri.encodeFull()`? since doing so will not change anything to a ascii string.

I have not seen such a reminder in the documents.

**Comment by lulupointu** [comment]
The path is a url and for url to be understood by web browser you must encode them.

You are right I should mention it in the doc !

Also you can use `context.vRouter.pushSegments(['/页面1'])` which will encode the url for you. This issue is that `VRouter` can NOT encode a url in `push` because `/` would be encoded as well. I could encode inbetween `/` but then someone might want it to be encoded. As you see there are no idea solution. But mentioning it in the docs is a good start :smile: 

Let me know if this answers your question !

**Comment by johnwangwjq** [comment]
Got it and thanks again. 

BTW, I guess by `pushSegments(['/页面1'])` you mean `pushSegments(['页面1'])`, ie., a forward slash should be omitted in a segment since `pushSegments` will add it for you.

**Comment by lulupointu** [comment]
Oh yes you are right ! I updated my answer for any future person coming here, thanks !
