### ISSUE TITLE
Support slivers as VWidget children

### ISSUE THREAD

**Issue by CosmicPangolin** [lulupointu/vrouter#93]
To build web-like scrolling views with a consistent header/footer/scroll indicator, I need my VNester widgetBuilder to wrap children in something like the following (using the sliver_tools package):

```
Scaffold(
  endDrawer: NavigationDrawer(),
  body: Stack(
    children: [
      InViewNotifierCustomScrollView(
        physics: SnapScrollPhysics(snaps: _snaps()),
        // No cacheExtent property for InView implementation...issue filed
        // cacheExtent: MediaQuery.of(context).size.height * 6,
        controller: _scrollController,
        isInViewPortCondition:
            (deltaTop, deltaBottom, viewPortDimension) =>
                deltaTop < (0.5 * viewPortDimension) &&
                deltaBottom > (0.5 * viewPortDimension),
        slivers: [
          SliverStack(
            children: [
              MultiSliver(
                children: [
                  widget.child,
                  Footer(),
                ],
              ),
              TransparentSliverHeader(),
            ],
          ),
        ],
      ),
      Align(
        alignment: Alignment.centerLeft,
        child: ScrollIndicator(),
      ),
    ],
  ),
),
```

In other words, the widget child that I need to pass in to populate a given route is just a SliverList.  This throws an error because VNester in particular expects every child to be a RenderBox :(

**Comment by lulupointu** [comment]
Hi, why not wrap `widget.child` in a sliver?

**Comment by CosmicPangolin** [comment]
@lulupointu Heya! I wish it were that easy :)

`widget.child` in my case is not just a RenderBox in a Sliver wrapper - it is a `SliverFixedExtentList`, which uses the `delegate: SliverChildListDelegate.fixed(<Widget>[...])` property to hold a list of unconstrained children that are scaled into slivers with fixed main and cross axis extents. This is necessary to efficiently build full-page slivers of content that interoperate well with a SliverAppBar and can also be appended with a final element `Footer()` using MultiSliver.  This is the only widgetBuilder-patterned construct that achieves my pretty basic goals - multiple routes of scrollable, full-screen elements nested within a single scaffold that has shared scroll behavior between lists of elements, a sliverappbar, and a footer.

If I were to pull `SliverFixedExtentList` into this wrapper, I would need to pass in a `List<Widget>` child through the widgetBuilder.  This wouldn't work with VNester either, since the widgetBuilder prop and nested VWidget expect a `widget` child.

The only workable hack is to use a `SliverToBoxAdapter(child: widget.child)` to wrap a  column with of individually sized children with `mainAxisSize: MainAxisSize.min`, which is not only less elegant code, it defeats the purpose of SliverList and particularly SliverFixedExtentList which are specially designed to be much more efficient for rendering collections of widgets in the viewport.  In my case with just a few sized video widgets in a Column, scrolling behavior is muuuch clunkier with with this solution...which is especially a problem since I have snapping physics for each page of scroll along the main axis (see [tesla website](www.tesla.com) for a very similar example).

Futher, using this scaffold with a SliverFixedExtentList child is valid render tree in Flutter and works if constructed as a unique VWidget, so the behavior of VNester is unnatural and incongruent the framework.  This feels a little similar to the Stack scaffold example from earlier where VNester just doesn't stitch wrapper and child together quite cleanly enough to be a sound generic solution.  Not sure if there's a deeper problem with the design, or maybe in this case it's just the need for a VSliver object?

**Comment by lulupointu** [comment]
The goal of `VNester` is to create a nested `Navigator` in which you can:
  1. Stack pages (with the ability to pop, have the right animations when pushing vs popping)
  2. Have animations when switching between pages

The point 1. does not make sense for slivers. What does it mean to stack slivers ?
The point 2. applies but transitions are based on routes which transition between widget. Therefore in this context an animation between sliver is not what a `Navigator` does.

Knowing that, it seems that `VNester` as little to no interest. The only useful think I could see is that you use relative paths and that you set the start of a path in `VNester` to not have to repeat it into each `nestedRoutes`. If you do need that tell me and I will show you how to use `VPath` which purpose is to do just that.

Now that we establish that `VNester` was not what you need, the question is *what do you need*.
What you need is a way to change the parameter of a widget depending on a path. You can parse the url for that, or use VRouter which goal it is to make that easier.

Here is a small example:

```dart
import 'package:flutter/material.dart';
import 'package:vrouter/vrouter.dart';

main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return VRouter(
      routes: [
        VWidget(
          path: '/',
          key: ValueKey('MainScreen'), // The key is the same to indicate that no transition of MainScreen should play between the two
          widget: MainScreen(child: HomeScreen()),
        ),
        VWidget(
          path: '/settings',
          key: ValueKey('MainScreen'), // Same key
          widget: MainScreen(child: SettingsScreen()),
        ),
      ],
    );
  }
}

class MainScreen extends StatelessWidget {
  final Widget child;

  const MainScreen({required this.child});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('This is the main screen')),
      body: child,
    );
  }
}

class HomeScreen extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Expanded(child: Center(child: Text('HomeScreen'))),
        ElevatedButton(
          onPressed: () => context.vRouter.push('/settings'),
          child: Text('Go to settings'),
        ),
        SizedBox(height: 100),
      ],
    );
  }
}

class SettingsScreen extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Expanded(child: Center(child: Text('SettingsScreen'))),
        ElevatedButton(
          onPressed: () => context.vRouter.push('/'),
          child: Text('Go to home'),
        ),
        SizedBox(height: 100),
      ],
    );
  }
}
```

Two interesting things to note:
  1. It's important to set the same `ValueKey` since you don't what the entire page to transition
  2. `child` is a widget but it could be children, a number... Even a sliver ! Whatever your heart desires :wink: 

Hope this helps!

**Comment by CosmicPangolin** [comment]
Yeah, thanks a ton....I think I see where my hangup has been.  I've expected the `widgetBuilder` result to be wrapped as a `PageRoute`, but in actuality the nested `VWidgets` are already wrapping their children with `Material/CupertinoPageRoute`.  And these classes in particular expect 'full-screen' RenderBox widgets....I think because to the implementation in their `TransitionMixins`?

Just out of curiosity to learn a bit deeper - given the base `PageRoute` is more flexible than the concrete `Material/CupertinoPageRoute`, and given stacking slivers are a possibility with `sliver_tools`(there is a class `SliverStack` that I use in the above example)...is it actually possible to construct a custom `PageRoute` that wraps a sliver and plays nicely with the `Navigator` API?  I would image yes, even without using `SliverStack`, because the Navigator seems pretty abstracted to handle an arbitrary list of `RouteEntries,' which itself seems to take an arbitrary `PageRoute.`.

That said, this makes me realize my construction is a bit silly because I wasn't imagining how the transition between `SliverLists` would look with the footer is injected through the scaffold.  This is the primary reason each page currently lacks its own `CustomScrollView`, and I think even if such a `PageRoute` could be constructed it'll be much easier and a more natural transition to duplicate the footer for each `ScrollView`.

**Comment by lulupointu** [comment]
The issue here is that `Navigator` is a widget. Since `VNester` child is basically a `Navigator` (with your `VWidget.widget` inside), it's not possible to use sliver, no matter what `PageRoute` outputs.

Something else entirely would be to make a `VSliverNester` which instead of a `Navigator` uses `SliverStack`. The issue then would be to create `VSliver` and to make sure that any `VRouteElement` inside `VSliverNester.nestedRoutes` is a `VSliver`.
This is actually possible but would require much work for little interest to most people.

I hope you will find what works best for you !

**Comment by CosmicPangolin** [comment]
Got it.  Thanks again, this was really helpful for me.
